asciidoctor/asciidoctorj

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlock.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlockImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/DocumentRuby.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Inline.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/TextConverter.java
Wile trying to move the reveal.js slim backend to a Groovy MarkupTemplateEngine based approach I needed to make these changes.
The members that are moved from AbstractBlock to AbstractNode are are also defined on AbstractNode in the Ruby implementation.
Some methods like DocumentRuby.doctitle() or AbstractNode.getAttr() were overloaded to mirror the defaults defined in the Ruby implementation.
> Aligned AST interfaces with Ruby definitions

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlock.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlockImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/InlineImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListItem.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListItemImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/NodeConverter.java
- asciidoctorj-core/src/main/java/org/asciidoctor/converter/ConverterProxy.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/TextConverter.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java
Also provided an implementation for the Inline interface.
Additionally moved Ruby to Java node conversion to separate class org.asciidoctor.ast.NodeFactory.
I tried hard for a DynamicProxy based approach and it worked fine for converters.
But the whole approach got mixed up when TreeConverters are added.
It seems to be impossible or at least very hard to mix and match JRuby type conversion and own DynamicProxies.
> Added new Java counterparts for List and ListItem nodes.

- asciidoctorj-core/src/main/java/org/asciidoctor/GlobDirectoryWalker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenGlobExpressionIsUsedForScanning.java
- asciidoctorj-core/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java
Absolute paths are split into an absolute part without wildcards that serves as the root directory and a relative part containing wildcards or at least the file name.
Relative paths are still handled as being reachable from current working dir.
> Fixes #275

- asciidoctorj-core/src/main/java/org/asciidoctor/GlobDirectoryWalker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenGlobExpressionIsUsedForScanning.java
- asciidoctorj-core/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java
Absolute paths are split into an absolute part without wildcards that serves as the root directory and a relative part containing wildcards or at least the file name.
Relative paths are still handled as being reachable from current working dir.
> Fixes #275.

- README.adoc
I created a section regarding the use of AsciidoctorJ in an OSGi environment.
I placed it after the *GEM_PATH* section mainly because the OSGi context is evoked in it, so I thought it might be the right place to be. wdyt?
> Adding a section for using AsciidoctorJ in an OSGi context in the README.

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/AbstractProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/DocinfoProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/IncludeProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/InlineMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PostprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/TreeprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyHashMapDecorator.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/internal/RubyHashMapDecoratorSpecification.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/GistMacro.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- build.gradle
- config/codenarc/codenarc.groovy
Currently the extension config is held redundantly in the Ruby part and in the Java part of an extension.
This leads to problems that config properties set in the Ruby part do not appear in the Java part and vice versa.
You can see the problem if you change the regular expression in the current test for an inline macro processor so that the extension should _not_ be applied. 
But it applies nevertheless because the regular expression does not translate into the Ruby part and therefore only the name is used.
This PR invents a RubyHashMapDecorator that wraps a RubyHash and decorates a `Map<String, Object>` around it, so that the `@config` member of the Ruby extension is also used in the Java part only with another view on it.
> Removed redundant config map from extensions.

- asciidoctorj-core/src/test/java/org/asciidoctor/extension/TerminalCommandTreeprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-core/src/test/resources/sample-with-terminal-command-and-gist-macro.ad
In the discussion around #267 @pmagon mentioned that he was not able to get a TreeProcessor running together with a BlockMacroProcessor.
This PR adds a test that proves that this configuration works.
Additionally the existing TerminalCommandTreeprocessor was changed to also convert terminal commands that are nested in sections.
> Test that TreeProcessor and BlockMacroProcessor can be used together

- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
The current solution to capture output from Asciidoctor and route it to a Java logger leads to infinite recursions and therefore StackOverflows when a ConsoleHandler is configured, which is the default in most configurations.
This problem is not reproducable with gradle as it replaces the normal System.out and System.err fields with own streams.
As Dan pointed out in #299 Asciidoctor will provide another solution that allows for capturing the output without having to read from System.out.
Therefore this PR completely removes capturing System.out and .err without replacement.
> Fixes #299: Removed rerouting of System.out and System.err to JUL

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/BlockProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/YellStaticBlock.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/YellStaticListingBlock.java
This PR is at the moment WIP!
It adds Javadoc for some config options for processors.
I added constants for `:contexts` config key and the values mentioned in (1).
I guess that this config parameter only makes sense with BlockProcessors.
If the location of the constants is correct I think I got it not too bad.
I added constants for `:content_model` and the values mentioned also mentioned in (1) to Processor.
I think this option makes also sense at least for a BlockMacro.
But I am very unsure about my comments and would like to get some feedback about the descriptions because I did not fully understand them yet.
(1) https://github.com/asciidoctor/asciidoctor-documentation/issues/30 to BlockProcessor.
(While typing this I always got the constant names incorrectly, so IMO it absolutely makes …
> Added javadoc for extension config options

- asciidoctorj-core/build.gradle
- build.gradle
Bumped the `jruby-gradle-base` plugin to `0.1.17` and the jruby version to `1.7.20`. This fixes the OOM that is seen when building under JDK6. It also adds all the performance improvements in jruby 1.7.20 to asciidoctorj.
This builds happily on my Mac with `1.6.0_65`.
> JRuby & jruby-gradle version bumps.

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Inline.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/InlineImpl.java
This adds a missing method for the Inline type. Anchors of type `link` require the `target` property.
> Adds target to inline

- asciidoctorj-pdf/build.gradle
- asciidoctorj-pdf/gradle.properties
Had to add manually copying content from the addressable gem, otherwise addressable-
/data/unicode.data is not available.
> Upgrade asciidoctor-pdf to 1.5.0-alpha7

- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenSlimTemplatesAreUsed.groovy
- asciidoctorj-core/src/test/resources/src/custom-backends/slim/block_paragraph.html.slim
- build.gradle
As Asciidoctor currently depends on sth slim 2.0.0-ish I chose to only upgrade to slim 2.1.0.
I added only a very basic test to see if the slim template is used at all.
It would probably be better to somehow check that really slim 2.1.0 is used...
> Fixes #307. Upgraded slim to 3.0.3 (was 2.1.0)

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/NodeConverter.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
Also overloaded Processor.createBlock() with methods that don't require an attributes parameter.
This PR mainly addresses some internal details.
At the moment to create a node an arbitrary String is passed to the NodeConverter.
This is changed by defining an enum that defines all supported node types.
Another side effect is that the classes are now no longer retrieved via `Ruby.evalScriptlet()` which is, as I guess, faster and more robust.
The methods `createBlock` and `createInline` are also overloaded to work without an attributes parameter as this is often an empty HashMap anyway.
> Use enums instead of arbitrary strings to create nodes.

- asciidoctorj-core/build.gradle
This just added some OSGi Metadata to the asciidoctorj-core.jar and makes it a OSGi bundle. That way, it can be loaded and used in OSGi environments as-is.
It does not add any special OSGi support, e.g. a `BundleActivator` or some service registrations. See also #297.
> Add OSGi metadata to asciidoctorj-core jar

- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenTwoAsciidoctorInstancesAreCreated.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/internal/WhenClassloaderIsRequired.java
This PR solves #339 
Instead of getting the Ruby instance from ScriptingContainer when passing a ClassLoader it is now always created via `JavaEmbedUtils.initialize()` and the classloader is passed to `RubyInstanceConfig.setLoader()`.
Personally I'd prefer to remove the factory method with a classloader completely, but we have to keep it because the ant plugin uses it, so I had to keep this method.
I think this way to initialize an Asciidoctor instance could be removed because:
1. Passing a classloader is equivalent to passing load paths (see https://github.com/jruby/jruby/wiki/ClasspathAndLoadPath#classpath-and-load-path-unification )
2. A new `RubyInstanceConfig` initially uses the current TCCL as classloader until it is reset (by `Asciidoctor.Factory.create(ClassLoader)` atm). So …
> Use only one way to initialize a Ruby instance

- appveyor.yml
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/ContentModel.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Contexts.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/DefaultAttribute.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/DefaultAttributes.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/DocinfoProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Format.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/FormatType.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/JavaExtensionRegistry.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Location.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/LocationType.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Name.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/PositionalAttributes.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/AbstractProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/DocinfoProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/IncludeProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/InlineMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PostprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PreprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/TreeprocessorProxy.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedBlockMacroProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedBlockProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedDocinfoProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedLongInlineMacroProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedRegexpInlineMacroProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAJavaExtensionIsRegisteredWithAnnotations.groovy
This should implement #196 
It is now possible to add these annotations:
- `@Name` to define block or macro names for BlockProcessors, BlockMacro- and InlineMacroProcessors
- `@ContentModel` to define the content model of a BlockProcessor
- `@Contexts` to define the contexts of a BlockProcessor
- `@DefaultAttribute` to define default attributes to pass to the process method of a processor
- `@DefaultAttributes` to define multiple `@DefaultAttribute`s on one type
- `@Location` to define where content generated by a DocinfoProcessor is to be placed.
`@PositionalAttributes` are missing yet because I am not aware what they should do.
In general the implementation adds options to the processors *class* object that serve as a default configuration for the instances. (see …
> Added annotation based processor configuration

- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-distribution/build.gradle
This is to make a start for #296 
This PR removes any setting of the ruby compat version or compile mode.
AsciidoctorJ will still run with the defaults and a user can now override the defaults if required.
> Removed default setting of any JRuby options

- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
One step further:
This PR parses the files `./.jrubyrc` and `~/.jrubyrc` when asciidoctorj is started via the CLI.
(IMO integrators should set these properties themselves, either use the same method or define own properties.)
Fortunately JRuby already provides a public static method to do this in `org.jruby.Main` that is simply used to accomplish this.
Additionally extended the version output (-V) to show the JRuby version and RUBY_VERSION.
> #296 Load JRuby properties from ./.jrubyrc and ~/.jrubyrc

- README.adoc
Describe that the JRuby runtime can be configured via `jruby.*` system properties or `.jrubyrc` files when launching via the shell script.
> Updated description of options for the JRuby runtime

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/DocinfoProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/IncludeProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PostprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PreprocessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/TreeprocessorProxy.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/ChangeAttributeValuePreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/CustomFooterPostProcessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/HasMoreLinesPreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/MetaRobotsDocinfoProcessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/NextLineEmptyPreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/NumberLinesPreprocessor.java
With changing the way processor classes get instantiated by AsciidoctorJ I removed the last map argument to the constructor call because there was simply no value in it.
AsciidoctorJ could only pass an empty map.
But removing this parameter would make existing processors incompatible.
So I readded the trailing map parameter again, always passing in an empty HashMap.
For a BlockProcessor registered as a class AsciidoctorJ will now call the constructors in this order:
1. String macroName, Map config
2. String macroName
3. no args
The first constructor that exists will be called.
The same mechanism applies for all other extensions.
> Readded support for processor constructors with a trailing map parameter

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Cell.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/CellImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/converter/TableTestConverter.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/GithubContributorsBlockMacro.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockMacroProcessorCreatesATable.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
- asciidoctorj-core/src/test/resources/githubcontributors.json
This PR adds support to create table cells with the asciidoc style.
These cells do not have content lines but have a nested document instead.
Therefore I
- added `Processor.createDocument(DocumentRuby parentDoc)` to create a nested document
- added `Processor.createTableCell(Column, DocumentRuby)` to create a cell with a nested document instead of content.
This is for example required to have images in tables.
> Support for creating tables with asciidoc style in extensions

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlock.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlockImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Cursor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/CursorImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
- asciidoctorj-core/src/test/resources/sourcelocation.adoc
This PR resolves #351 
I added a method `AbstractBlock.getSourceLocation()` that returns a `org.asciidoctor.ast.Cursor`.
> Source location

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/PreprocessorReader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/PreprocessorReaderImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Reader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/ReaderImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/IncludeProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PreprocessorProxy.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorIsRegistered.groovy
At the moment Reader and PreprocessorReader are still the "simple" Ruby wrapper objects with their drawbacks.
For example PreprocessorReader.document() will return a Ruby wrapper again instead of THE Document object that all other AST objects return.
> Add own proxying for Reader and PreprocessorReader.

- README.adoc
- build.gradle
- gradle/deploySnapshot.gradle
- gradle/publish.gradle
I managed to upload a snapshot version of the asciidoctorj.jar with this via `./gradlew :asciidoctorj:artifactoryPublish`.
But it fails for other projects like the EPUB converter or the test-support project if I want to publish everything with a HTTP 409 (Conflict).
I don't really understand how it is all connected, gradle publishing, the nebula publishing plugin and now the artifactory plugin.
But I thought I already open a PR so that somebody could possibly help bringing this forward.
(And I just don't understand why the binary plugin and the artifactory plugin have to be so different, I mean it's the same company...)
> WIP: Publish Snapshot builds

- test-asciidoctor-upstream.sh
Add a blank extension value to the `-i` flag when invoking `sed` so that it works on OSX. This should work in theory, but I haven't tested it yet on an OSX box.
The same patch should be applied to the master branch.
> add fix to upstream test script for OSX

- asciidoctorj-pdf/build.gradle
- downgrade the thread_safe version to 0.3.4
- remove out of date hacks for Asciidoctor PDF 1.5.0.alpha.8
> convince Asciidoctor PDF to use the thread_safe provided by AsciidoctorJ

- README.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Preprocessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/PreprocessorProxy.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorIsRegistered.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/ChangeAttributeValuePreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/HasMoreLinesPreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/NextLineEmptyPreprocessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/NumberLinesPreprocessor.java
As discussed in #383 it doesn't make much sense at the moment to let `Preprocessor.process()` return anything useful as both `null` and the given `PreprocessorReader` have the same result. 
And with AsciidoctorJ it is atm impossible to create own Readers and it is generally not trivial to create them facing the state that they hold.
Therefore this PR changes the return type of `Preprocessor.process()` to `void`.
!!! This makes existing Preprocessors incompatible and requires a change when upgrading to 1.6.0!
> Fixes #383: Change return type of Preprocessor.process() to void

- .travis.yml
- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/test/java/org/asciidoctor/internal/WhenClassloaderIsRequired.java
- asciidoctorj-diagram/build.gradle
- asciidoctorj-epub3/build.gradle
- asciidoctorj-pdf/build.gradle
- build.gradle
- gradle/eclipse.gradle
Bumped JRuby version to 9.0.3.0.
As JRuby only works with Java >= 7 I also bumped the source and target version of AsciidoctorJ to 1.7.
Additionally changed the dependency from `ruby-complete` to `jruby` which fixes #230.
With this the lib directory of the distribution looks like this:
```
asciidoctorj-1.6.0-SNAPSHOT.jar
asciidoctorj-epub3-1.5.0-alpha.4.jar
asciidoctorj-pdf-1.5.0-alpha.9.jar
bytelist-1.0.13.jar
dirgra-0.3.jar
high-scale-lib-1.0.6.jar
invokebinder-1.5.jar
jcodings-1.0.13.jar
jcommander-1.35.jar
jffi-1.2.9-native.jar
jffi-1.2.9.jar
jnr-constants-0.9.0.jar
jnr-enxio-0.9.jar
jnr-netdb-1.1.4.jar
jnr-posix-3.0.19.jar
jnr-unixsocket-0.8.jar
jnr-x86asm-1.0.2.jar
joda-time-2.8.2.jar
joni-2.1.8.jar
jruby-9.0.3.0.jar
jruby-core-9.0.3.0.jar
jruby-stdlib-9.0.3.0.jar
jzlib-1.1.3.jar …
```
> Changed dependency on JRuby to 9.0.3.0.

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ContentNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/ContentNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/LocationType.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAJavaExtensionIsRegisteredWithAnnotations.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/TerminalCommandTreeprocessor.java
- build.gradle
- docs/integrator-guide.adoc
Also added new methods addRole() and removeRole() that became part of Asciidoctor 1.5.3.
Adapted to change of DocinfoProcessor option for adding Docinfo to the header (:header -> :head).
When this PR is merged I'd like to cut an Asciidoctor 1.6.0-alpha release.
Then we do not only make a difference internally to 1.5.2 but also by the numbers:
Asciidoctor 1.5.2 -> 1.5.3
JRuby 1.7.x -> 9.0.3.0
Java 6 -> 7
> Bump version of Asciidoctor to 1.5.3 and fixes #393.

- asciidoctorj-diagram/gradle.properties
As there is a new release of asciidoctor-diagram, let's use this version instead of the previous preview one.
> Update asciidoctor diagram from version 1.3.0.preview.1 to 1.3.0

- asciidoctorj-core/src/test/java/org/asciidoctor/WhenSlimTemplatesAreUsed.java
- asciidoctorj-core/src/test/resources/src/custom-backends/slim/block_paragraph.html.slim
- build.gradle
We already went to slim 3.0.3 on the 1.6.0 branch.
This should upgrade the slim dependency to the most recent version 3.0.6 on the master branch to prepare a 1.5.3 release.
> Bump slim to 3.0.6

- asciidoctorj-distribution/build.gradle
- asciidoctorj-distribution/src/test/groovy/org/asciidoctor/diagram/WhenDitaaDiagramIsRendered.groovy
- build.gradle
#401 has shown that JRuby behaves differently when loading gems from a jar or from an exploded directory.
The current test cases for diagram and pdf only refer to the exploded gems which does not reflect the way gems are loaded by a user, i.e. "in production".
I added a test case to asciidoctorj-distribution that creates a ditaa diagram, very similar to the test in asciidoctorj-diagram.
But as asciidoctorj-diagram is referenced as a dependency, the gem will be loaded from a jar.
#401 can be reproduced with this PR when setting the JRuby version to 1.7.22.
> Fixes #405. Adds integration tests to asciidoctorj-distribution.

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/DescriptionList.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/DescriptionListEntry.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/NodeConverter.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/DescriptionListEntryImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/DescriptionListImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyBlockListDecorator.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyObjectWrapper.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenADocumentContainsADefinitionList.groovy
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/ASTExtractorTreeprocessor.java
- docs/integrator-guide.adoc
I created two new classes in the AST package:
`DefinitionList` is a `StructuralNode` and contains `DefinitionListItem`s.
`DefinitionListItem` has a list of `definitionTerm`s, that are `ListItem`s, and a `definition`, that is also a `ListItem`.
But a `DefinitionListItem` is not a `ContentNode`.
And that's maybe not so nice, because `DefinitionList.getBlocks()` returns a list of `StructuralNode`s per its signature.
In fact the members are `DefinitionListItem`s and therefore no `StructuralNode`s.
> WIP: Fixes #404. Add AST types for definition lists.

- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAnAsciidoctorClassIsInstantiatedInAnEnvironmentWithGemPath.java
- asciidoctorj-core/src/test/java/org/asciidoctor/categories/Polluted.java
Fixes #419 for the 1.6.0 branch.
Contains the same commits as #420.
Made a new PR as the tests revealed a new error in the 1.6.0 branch that I want tested on the CI system before merging: 
A null gemPath passed to `Asciidoctor.Factory.create((String) null)` was completely ignored so that a `GEM_PATH` still leaked into the JRuby instance!
> Fix for Issue 419

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/IncludeProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/InlineMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyAttributesMapDecorator.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyHashMapDecorator.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AttributeCheckingBlockProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAJavaExtensionChecksAttributes.groovy
Instead of simply passing the RubyHash as converted by JRuby to the processor this PR creates a RubyAttributesMapDecorator and passes this instead.
The RubyAttributesMapDecorator encapsulates the original RubyHash.
> Fixes #450, Pass a RubyAttributesMapDecorator to Processors.

- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyHashMapDecorator.java
One test currently fails with JRuby 9.1.0.0 with this exception:
```
java.lang.NullPointerException
at org.jruby.java.proxies.MapJavaProxy$RubyHashMap.visitAll(MapJavaProxy.java:261)
at org.jruby.RubyHash.replaceCommon(RubyHash.java:1870)
at org.jruby.RubyHash.replace(RubyHash.java:1845)
```
This is due to `RubyHashMapDecorator.size()` not returning the exact result if the wrapped map contains entries (e.g. positional parameters) that are filtered and not added to the iterator.
This PR fixes `size()` and `isEmpty()` to work correctly even with positional attributes.
> Avoid NPE with JRuby 9.1.0.0

- asciidoctorj-arquillian-extension/build.gradle
- asciidoctorj-distribution/build.gradle
- build.gradle
- gradle/publish.gradle
- gradle/signing.gradle
I think I found a solution to make the pom generation work again.
Something is strange. I should not have to add the publishing configuration block into afterEvaluate.
But it works that way with the current configuration in the 1.6.0 branch.
Before the pom where generated too, but without the dependencies block o.O
> Asciidoctorj 1.6.0 - pom generation fix

- gradle/deploy.gradle
- gradle/publish.gradle
The bintray plugin allows two ways to define the artifacts to be uploaded.
* Maven Publications
* Configurations
We use both, as it is not possible to add the signatures for the jars to the maven publication.
(Or maybe it is possible, but I couldn't figure out how. Adding the signed artifacts to the publication like adding the
pom signature failed with an error while publishing to maven local.)
The _archives_ configuration holds the jar-artifacts and the signatures. And that is why the jar artifacts are doubled and the signatures not.
Defining the _signatures_ configuration is the solution for every non distribution module.
One thing I was not able to prevent from uploading twice is the pom file.
But I think that is tolerable.
(Maybe it is not supposed to mix those two definitions and …
> prevent multiple upload of artifacts to bintray

- asciidoctorj-core/gradle.properties
- asciidoctorj-diagram/gradle.properties
- asciidoctorj-epub3/gradle.properties
- asciidoctorj-pdf/gradle.properties
- build.gradle
- gradle/versioncheck.gradle
Wrote a little helper task called _checkVersion_ to keep track of published gem versions.
Here is an example of the tasks output:
```
gradle checkVersion
Configuration(s) specified but the install task does not exist in project :asciidoctorj-distribution.
:asciidoctorj:checkVersion
up-to-date
:asciidoctorj-diagram:checkVersion
WARNING
Version mismatch: Current Version: 1.3.1, Gem Version: 1.4.0
:asciidoctorj-epub3:checkVersion
up-to-date
:asciidoctorj-pdf:checkVersion
up-to-date
BUILD SUCCESSFUL
```
It prints a brief warning for each project which version is less than the published gem.
You can skip the the check with `-P skip.checkVersion`
The task is disabled in offline mode.
Maybe it helps.
> add checkVersion Task to keep track of published gem versions

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Cell.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/CellImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Column.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/ColumnImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/NodeConverter.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Row.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/RowImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/Table.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/TableImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenStructuredDocumentIsRequired.java
This PR fixes #472 by adding interfaces and classes for Tables to the AST classes.
In contrast to the imply in the AsciidoctorJ 1.6.0 branch however this does not add support for creating Tables from a Processor.
This would imo require to downport all changes made on the AST classes for the 1.6.0 branch to 1.5.x.
> Fixes #472. Add support for Tables in AST.

- asciidoctorj-diagram/gradle.properties
- asciidoctorj-diagram/src/test/java/org/asciidoctor/WhenDocumentContainsDitaaDiagram.java
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenDitaaDiagramIsRendered.java
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenPlantumlDiagramIsRendered.java
Apparently the cache files are no longer located in the `imagesoutdir` but in the current working directory below `.asciidoctor/diagram/`.
> Fixes #473. Upgrade asciidoctor-diagram to 1.5.0.

- gradle/versioncheck.gradle
Prevent stopping  check Task if an exception happens during checkVersion execution.
Print proper warning message if a version violates semantic versioning.
Closes #479
> Failsafe version of checkVersion Task

- .travis.yml
- asciidoctorj-distribution/build.gradle
- gradle/deploy.gradle
- gradle/publish.gradle
- gradle/signing.gradle
- test-asciidoctor-upstream.sh
> fix pom generation for release versions to prevent adding a pom packaging tag

- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- use filename instead of content where appropriate
- replace tabs with spaces
- drop unnecesary empty brackets for methods that take no parameters
> fix parameter names in internal Ruby API

- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
method_defined? is the correct method to use to detect an existing
method definition, not respond_to?
> use method_defined? instead of respond_to?

- asciidoctorj-distribution/build.gradle
- build.gradle
- gradle/sdkman.gradle
Configure your local gradle.properties file with the following credentials.
* sdkman_consumer_key=_some_key_
* sdkman_consumer_token=_some_token_
Adds the following Tasks to the configuration if project status is 'release'.
See project.statusIsRelease.
* _sdkAnnounceVersion_ - Announce a Release on SDKMAN.
* _sdkDefaultVersion_ - Make an existing Candidate Version the new Default on SDKMAN.
* _sdkReleaseVersion_ - Release a new Candidate Version on SDKMAN.
* _sdkMajorRelease_ - Convenience task performs a Major Release consisting of Release, Default and Announce combined.
* _sdkMinorRelease_ - Convenience task performs a Minor Release consisting of Release and Announce combined
See https://github.com/sdkman/sdkman-vendor-gradle-plugin for more information.
> added sdkman verndors plugin

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/StructuralNodeImpl.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenSubstitutionsAreUsed.groovy
This PR adds methods to 
- get the active substitutors of a node `getSubstitutions()`
- to query if a substitutor is active `isSubstitutionEnabled()`
- and to remove a substitute `removeSubstitution()`
I could not find a method though to prepend or append a substitutor in the current Ruby API and directly adding the symbol to `@subs` did not work.
I guess to add a substitution at the moment it is necessary to pass the corresponding option to the node.
> Fixes 501: Added method to get and remove substitutions

- .gitignore
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/CellImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/StructuralNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyHashUtil.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenATableIsLoaded.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockProcessorCreatesABlockThatATreeProcessorVisits.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
Sorry to submit multiple changes in one pull request (and not using branches), but I had to make these changes in quick succession and could not isolate them. They are independent of each other, however. There are three changes:
**Convert nested Java maps to Ruby hashes in `RubyHashUtil#toRubyObject`**
This prevents a `ClassCastException` when, after creating a new block in a block processor, you attempt to access the attributes of that block later in a tree processor. When asking the block for its attributes, AsciidoctorJ assumes that what it gets from the asciidoctor AST is an instance of `RubyHash`, when in this case what it really gets is an instance of ` MapJavaProxy` that was injected by JRuby into the asciidoctor AST when the block was created originally.
I'm not sure about this …
> Multiple small changes

- asciidoctorj-distribution/build.gradle
- asciidoctorj-pdf/build.gradle
- build.gradle
- Fixes #530: Add the change proposed by @abelsromero 
- Fixes #533: Add fixed dependencies for then gems `addressable` and `public_suffix`
- Also upgrades the version  of jruby to 1.7.26
> Fix master build and distribution classpath

- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
- asciidoctorj-distribution/src/test/groovy/org/asciidoctor/diagram/WhenDitaaDiagramIsRendered.groovy
Fixes the first and third issues mentioned in https://github.com/asciidoctor/asciidoctorj/pull/550#issuecomment-299573561.
Fixes only affect test assertions so they work both for *nix and Windows.
> Fixes assertions for some test that failed on  Windows 7 and Windows 8.1

- README.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/ExtensionGroup.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/RubyExtensionRegistry.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/AsciidoctorModule.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/ExtensionGroupImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionIsRegistered.java
- asciidoctorj-diagram/gradle.properties
- asciidoctorj-diagram/src/test/java/org/asciidoctor/WhenDocumentContainsDitaaDiagram.java
- asciidoctorj-distribution/build.gradle
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenDitaaDiagramIsRendered.java
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenPlantumlDiagramIsRendered.java
- asciidoctorj-epub3/gradle.properties
- asciidoctorj-epub3/src/test/java/org/asciidoctor/WhenEpub3BackendIsUsed.java
- build.gradle
- gradle.properties
This PR updates Asciidoctor core to 1.5.6 and Asciidoctor-Diagram to 1.5.5.
(Asciidoctor 1.5.6 will not run with any other version Asciidoctor-Diagram – see asciidoctor/asciidoctor-diagram#154 and asciidoctor/asciidoctor-diagram#159)
To fix asciidoctor/asciidoctor-diagram#159 the TCCL is changed while rendering the document to the current JRubyClassLoader. This is necessary because asciidoctor-diagram requires access to other jars in that gem via the TCCL.
This might impact extensions though, that require the TCCL to be set to sth else, possibly extensions that run in a JavaEE environment. I can't say anything about how OSGi class loading would be impacted due to my lack of knowledge.
What is missing though is the update to the latest epub3 converter, the first test failed and I'll look …
> Upgrade to Asciidoctor 1.5.6 and Asciidoctor-Diagram 1.5.5

- README.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/ExtensionGroup.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/RubyExtensionRegistry.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/AbstractProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/AsciidoctorModule.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/ExtensionGroupImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockMacroProcessorCreatesASection.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAJavaExtensionGroupIsRegisteredWithAnnotations.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionIsRegistered.java
This PR brings the ExtensionGroup API to the 1.6.0 branch.
It seems that I got it wrong on the current master by assuming that I can do multiple executions of `Asciidoctor::Extensions.register` with the same groupName.
If I didn't get it wrong it overwrites a previous registration.
Therefore I hopefully fixed it here by collecting all extensions in list or maps per type and the registering them in one go in the Ruby code (asciidoctorclass.rb).
There was also an error with multiple executions of extensions that were registered as instances.
For these it was tried to call `setConfig` twice which was rejected with an IllegalStateException. I fixed this by adding a method `updateConfig` that can be executed multiple times and add to the existing config.
In such a case it is probably not …
> Add ExtensionGroup API and fix registration of multiple extensions

- .travis.yml
Just sets the `precise` as image.
Still uses JDK available for that image, note that oraclejdk7 is not compatible with new `trusty` image.
> fixes #575 - forces TravisCI to use precise image

- .travis.yml
At one time, the defaults for the notifications were annoying. Now they are reasonable and we depend on them being sent.
I reverted to the default, though I'm not sure if we need to set anything to get notifications in the gitter channel. Here's the template if we do need that:
```yml
notifications:
webhooks:
urls:
- https://webhooks.gitter.im/e/3b53badb62267d16b33a
```
> reenable CI notifications

- .gitattributes
- README.adoc
- chocolatey/README.adoc
- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
- chocolatey/tools/chocolateyuninstall.ps1
A while back I created a [Chocolatey package for AsciidoctorJ](https://chocolatey.org/packages/asciidoctorj/), which makes getting Asciidoctor up and running on Windows much easier (for me at least). It installs the asciidoctorj-x.y.z-bin.zip bintray package as well as a wrapper for asciidoctorj.bat in %ChocolateyInstall%\bin
This PR contains the files I used to create the package.
> Add Chocolatey packaging.

- asciidoctorj-distribution/build.gradle
Manual tests on Windows showed that 9.1.13.0 seems to run fine.
Therefore upgrade the version in the distribution from 9.1.8.0 to 9.1.13.0.
> Bump JRuby version for the distribution to 9.1.13.0

- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
The upstream build fails due after the changes to Asciidoctor wrt mkdir.
This PR fixes the test by explicitly setting the mkDirs option to true for that test.
> Fix upstream build failing due to changes in behavior of creating dirs

- asciidoctorj-core/src/main/java/org/asciidoctor/ast/NodeConverter.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
The reported bug was due to a node method returning nil.
The NodeConverter didn't properly distinguish this result and tried to convert it instead of simply returning null.
> Fixes #593. Handle nil result from node methods correctly

- appveyor.yml
The Graphviz binaries have moved to a new location, letting the installation of the chocolatey packages fail on Appveyor.
Let's check if the installation of the "normal" graphviz chocolatey package succeeds which already seems to use the new location: https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/graphviz/update.ps1
> Try to install graphviz msi instead of graphviz.portable on Appveyor

- .gitignore
- asciidoctorj-core/src/main/java/org/asciidoctor/converter/ConverterProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/RubyOutputStreamWrapper.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenADocumentIsRenderedToStream.groovy
- asciidoctorj-distribution/src/test/groovy/org/asciidoctor/diagram/WhenAPdfDocumentIsRenderedToStream.groovy
- build.gradle
This PR tries to fix #588 as well as rendering HTML to OutputStreams.
The key is to wrap the OutputStream into sth that implements methods like `write` (used by Asciidoctor core) and `<<` and `size` (used by pdf-core).
Direct calls of `write` to an OutputStream don't work from Ruby because the method is overloaded and JRuby can't figure out which one to call.
I don't know if I messed up encodings, because I just get RubyStrings in and I simply convert them to bytes without using an encoding. Do I have to pass in an encoding that is available somewhere.
PDF generally works but in comparison to rendering to a File the title page is missing.
@mojavelinux Is there any chance that this is not an error in this PR but the normal behavior of Asciidoctor-PDF under certain circumstances?
> Fixes #588. Fix rendering to Java streams

- asciidoctorj-core/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
Fixes #616 on master.
The handling of the showTitle attribute wasn't correct.
When showTitle is true, the `showtitle` attribute has to be set to any value.
When showTitle is false, the `notitle` attribute has to be set to any value. 
If this is ok I will propose another PR on asciidoctorj-1.6.0.
> Fixes #616. Fix handling of showTitle attribute

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/MacroProcessor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/ManpageMacro.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/internal/WhenClassloaderIsRequired.java
Looks like we had differing method declarations for the process methods on the different extension types and JRuby 9.1.15.0 on Java 9 doesn't like to call protected methods.
This PR fixes this by making these methods public like they are on other extensions as well.
To test change the version of JRuby in build.gradle to 9.1.15.0 and run the build with Java 9.
It should fail without this PR and succeed with this PR.
> Fixes #624. Fix issues with JRuby 9.1.15.0 on Java 9

- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/TableUpdaterTreeProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenATreeProcessorWorksOnTables.groovy
This PR adds an explicit test that updating a table cell from a Treeprocessor works.
See questions to #523
> #523 Add explicit test for updating table cell source

- asciidoctorj-distribution/build.gradle
As reported by Russel Winder on Twitter the AsciidoctorJ tool crashes right after the start on OpenJDK 10 due to the JVM option `-XX:+UseFastAccessorMethods`.
This PR simply removes this flag.
While it might make AsciidoctorJ a bit slower when started from the command line, it's still better than not starting at all.
And it shouldn't hurt, because this flag isn't set anyway when running for example as part of the Maven plugin.
> Fix start error for asciidoctorj tool on OpenJDK 10

- asciidoctorj-diagram/gradle.properties
Simply upgrades asciidoctor-diagram to the latest version 1.5.9
> Upgrade asciidoctor-diagram to 1.5.9

- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/ast/impl/CursorImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Contexts.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/LogHandler.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/LogRecord.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/Severity.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/internal/JULLogHandler.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/internal/JavaLogger.java
- asciidoctorj-core/src/main/java/org/asciidoctor/log/internal/LogHandlerRegistryExecutor.java
- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/groovy/org/asciidoctor/internal/RubyAttributesMapDecoratorSpecification.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/MemoryLogHandler.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/log/TestLogHandlerService.java
- asciidoctorj-core/src/test/resources/META-INF/services/org.asciidoctor.log.LogHandler
- asciidoctorj-core/src/test/resources/documentwithinvalidrefs.adoc
- asciidoctorj-core/src/test/resources/documentwithnotexistingfile.adoc
- build.gradle
- gradle.properties
This PR ports the changes in #643 to the 1.6.0 branch.
Like in that PR there custom log receivers can be implemented as `org.asciidoctor.log.LogHandler` and by default these entries are also forwarded to JUL.
Also the `$VERBOSE` variable is always set to `true` to always notify messages for invalid references.
> Add plugin mechanism for Loggers

- asciidoctorj-distribution/build.gradle
Using `org.jruby:jruby` for the distribution dumps a lot of libs in the `lib/` folder of the bistro.
As overriding of transitive dependencies is not that important for the distribution, this PR uses `jruby-complete` in that case.
> Package jruby-complete in distribution

- chocolatey/README.adoc
- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
Use a stronger hash and add an iconUrl while we're here.
> Chocolatey: Update to AsciidoctorJ 1.5.7.

- README.adoc
This PR adds a small documentation to explain how to register custom LogHandlers.
**This is WIP and before merge** I'd like to understand a couple of things I found in my tests in order to document them properly.
* paths in the `Cursor` are absolute always, I tried with relative Files and Strings. Is that expected?
* Some names are confusing to me: check the docs for the use of cursor.path, cursor.file and sourceFilename. Specially the latests. Is that also normal? If `sourceFilename` is always <script>, does it make sense to expose it?
> Adds LogHandler documentation to README

- README.adoc
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- docs/integrator-guide.adoc
Updates README.
Should also update https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc, or include it?
> Adds LogHandler documentation to README (branch 1.6.0)

- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
Same as #676 for the 1.6.0 branch:
As discussed in #667 this PR removes setting the global variable `$VERBOSE` to true again.
This avoids the warnings produced by JRuby when loading the prawn and ttfunk gems:
```
uri:classloader:/gems/prawn-svg-0.27.1/lib/prawn/svg/color.rb:212: warning: shadowing outer local variable - result
uri:classloader:/gems/prawn-svg-0.27.1/lib/prawn/svg/properties.rb:50: warning: `*' interpreted as argument prefix
Aug 18, 2018 7:14:58 PM <script> convertFile
WARNUNG: invalid reference: foo
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: warning: instance variable @offset not initialized
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: warning: instance variable @offset not initialized
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: …
```
> Remove setting  again to avoid JRuby warnings

- asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/java/org/asciidoctor/QandATest.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
As discussed in #667 this PR removes setting the global variable `$VERBOSE` to true again.
This avoids the warnings produced by JRuby when loading the prawn and ttfunk gems:
```
uri:classloader:/gems/prawn-svg-0.27.1/lib/prawn/svg/color.rb:212: warning: shadowing outer local variable - result
uri:classloader:/gems/prawn-svg-0.27.1/lib/prawn/svg/properties.rb:50: warning: `*' interpreted as argument prefix
Aug 18, 2018 7:14:58 PM <script> convertFile
WARNUNG: invalid reference: foo
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: warning: instance variable @offset not initialized
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: warning: instance variable @offset not initialized
uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:26: warning: instance variable @offset …
```
> Remove setting verbose mode to prevent logging of JRuby warnings

- asciidoctorj-distribution/build.gradle
- build.gradle
#680 indicates that there's a problem with JRuby 9.1.16.0 that lets AsciidoctorJ fail when the same document is rendered 100's of times.
It looks like 9.1.17.0 fixed this.
Therefore this PR bumps the version of JRuby to 9.1.17.0 for the 1.5.x branch
The 1.6 branch is already on 9.2.0.0, which is incompatible with 1.5.x.
> Bump version of JRuby to 9.1.17.0 for 1.5.x

- asciidoctorj-core/src/test/java/org/asciidoctor/WhenMultipleDocumentsAreRendered.java
This PR ports #682 to the 1.6.0 branch.
If it works we know that the problem with JRuby 9.1.16.0 is also fixed with 9.2.0.0.
> added test to reproduce issue with jRuby 9.1.16.0

- asciidoctorj-diagram/gradle.properties
This PR bumps asciidoctor-diagram to 1.5.10.
If the CI build is green I'll try to create a release of this module next week.
> Bump asciidoctor-diagram to 1.5.10

- asciidoctorj-core/build.gradle
This PR adds the sources of asciidoctorj-api to the sources for generating the javadocs of asciidoctorj.
With this the AST interfaces should be visible again in  http://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/1.6.0-alpha.8 (once we release this version)
I guess if we manage to fully migrate everything "dev-facing" or "user-facing" into the API module, it would make more sense to only have the javadocs for this instead of the asciidoctorj module. But we're not there yet.
> Fixes #686. Add sources of asciidoctorj-api to javadocs of asciidoctorj

- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java
This PR adds the `-t / --timings` option to the 1.6.0 branch. #695 is the corresponding PR for 1.5.x.
It also fixes collecting the timings which was previously tied to the `--verbose` option.
> Add flag for timings mode and fix it

- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java
This PR adds a `-t` command line option to align with the original `asciidoctor` command.
Previously the timings should've been printed when starting with `-v` (verbose mode).
But it looks like this didn't even work, as the timings are now managed by the `Asciidoctor::Timings` class which has to be present in the options.
I fixed this by explicitly creating such an instance, and then after the rendering calling this to print its report, so that the report should also look identically to what asciidoctor produces.
Along the way I also found an error in the tests regarding the destination dir option `-D`.
The test `destination_dir_should_render_files_to_ouput_directory()` also fails on the current master when running in isolation.
It only succeeded because the test …
> Add timings command option and fix timings

- asciidoctorj-core/build.gradle
- build.gradle
This PR adds the gem concurrent-ruby to the AsciidoctorJ jar that I missed in the 1.5.8 release.
After merging this I would create a new release 1.5.8.1.
> Add concurrent-ruby gem to AsciidoctorJ jar

- asciidoctorj-wildfly-integration-test/build.gradle
- asciidoctorj-wildfly-integration-test/src/test/java/org/asciidoctor/AsciidoctorServlet.java
- asciidoctorj-wildfly-integration-test/src/test/java/org/asciidoctor/WildflyIntegrationTest.java
- asciidoctorj-wildfly-integration-test/src/test/java/org/asciidoctor/categories/Wildfly.java
- asciidoctorj-wildfly-integration-test/src/test/resources/MANIFEST.MF
- asciidoctorj-wildfly-integration-test/src/test/resources/arquillian.xml
- asciidoctorj-wildfly-integration-test/src/test/resources/module.xml
- build.gradle
- settings.gradle
This PR adds an integration test for Wildfly, which is special for AsciidoctorJ due to the jboss modules class loading.
As the Arquillian Wildfly seems to require an external installation this test currently can only be executed locally after installing Wildfly.
I was not aware that a Wildfly distribution can be downloaded from Maven central.
To run the test execute:
```
./gradlew clean integrationTest -Pjboss.home=<path to wildfly>
```
Thanks to @mgreau for providing the blueprint for this in the docker-asciidoctorj repo!
> Add wildfly integration test

- asciidoctorj-documentation/build.gradle
Because asciidoctorj-pdf depends on jruby-complete.jar and asciidoctorj now depends on jruby.jar, both jars appeared in the dependencies, and to make it even worse with 2 different versions.
That cause the build error of asciidoctorj-documentation on Appveyor.
> Fix build of integrator guide on Windows

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/BlockProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Contexts.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/ConfigModifyingBlockProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenTheConfigIsSetOfAJavaExtension.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/YellStaticListingBlock.java
- @deprecated BlockProcessor context constants (replaced by Contexts)
- should we remove Processor constants ?
- Use diamond where possible `Map<String, String> config = new HashMap<>()`
- Reformat code (tabs -> spaces)
> Replace deprecated constants and methods in the extension package

- README.adoc
Since version `1.5.7` of asciidoctorj, the given snippets for using it in an OSGi didn't work anymore as the JRuby dependency has changed to version 9.x. This make the use of the RubyInstanceConfig useless and not working.
Moreover, the load path passed to the `JavaEmbedUtils#initialize` should be prefix with `uri:classloader`. I didn't find another solution for make it work. The solution has been integrated in [SlideshowFX](https://github.com/twasyl/SlideshowFX/blob/dae814bfbc6bccbf09033adc8223d97ab41d18d3/slideshowfx-asciidoctor/src/main/java/com/twasyl/slideshowfx/markup/asciidoctor/AsciidoctorMarkup.java#L28) using asciidoctorj 1.5.8.1.
Also update the artifact version in the documentation.
> OSGi snippets update

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/BlockMacroProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/DocinfoProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/ExtensionGroup.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/IncludeProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/InlineMacroProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/MacroProcessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Postprocessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Preprocessor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/Treeprocessor.java
A little code cleanup in the extension package (to reduce the code changes in #715).
If you want to do a single commit to use diamond operator everywhere I can do it. I can also remove the unnecessary `public` keyword from interfaces at once ?
> Use diamond, remove unnecessary public keyword on interfaces

- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Contexts.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/DefaultAttribute.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/DefaultAttributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Format.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/FormatType.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Location.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/LocationType.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Name.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/PositionalAttributes.java
I had to remove javadoc `@link` on `*Processor` classes because we cannot move them without decoupling the implementation (see #715).
Apart from that, I think it's safe to merge.
> Move extension annotations and enums to the API module

- build.gradle
Looks like the JRuby release train is rolling fast atm.
So here is the next bump.
> Bump JRuby to 9.2.4.0

- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/internal/WhenClassloaderIsRequired.java
This PR reverts #712 again.
Apparently (see #721) the create methods that take a Classloader are required to use AsciidoctorJ in OSGi environments.
Until we can offer alternatives we should therefore keep these methods.
> Revert #712

- .travis.yml
- appveyor.yml
I successfully built AsciidoctorJ locally with OpenJDK 11.
Let's cross fingers that it works on the ci systems as well.
There's probably not much value anymore running tests with Java9 which is already eol.
> Run ci build with Java 11

- asciidoctorj-documentation/src/main/asciidoc/extension-migration-guide.adoc
- docs/extension-migration-guide.adoc
This PR adds a documentation explaining the changes necessary to migrate an extension from 1.5.x to 1.6.
I didn't add a tested documentation yet, I don't know if it's worth the effort to also test the 1.5.x extension against 1.5.x.
> Add extension migration guide

- asciidoctorj-core/src/main/java/org/asciidoctor/extension/JavaExtensionRegistry.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/BlockProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/extension/processorproxies/InlineMacroProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/internal/JavaExtensionRegistryImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/BlockMacroRegistrationTest.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/BlockProcessorRegistrationTest.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/InlineMacroRegistrationTest.java
This PR fixes #754.
Before merging this I will also have to fix the same problem for macros, as they like have it as well.
> Fixes #754. Initialize BlockProcessor.name correctly

- README.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
- Update OSGI snippet in both README and JavaDoc because the behaviour has changed in 1.6.0
- Update artifact-version to 1.6.1
> OSGI update

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/BaseProcessor.java
This PR fixes #754.
In OSGi environments the TCCL seems to be set in a way so that the Processor service class cannot be found by java.util.ServiceLoader.
Added a fallback to also use the class loader of the local class.
> Fix initialization of extension in OSGi environments

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/log/internal/JavaLogger.java
- build.gradle
In addition to only bumping the version of JRuby there is also a change of an internal API for the backtrace elements.
The PR aligns to this so that AsciidoctorJ 1.6.2 will be incompatible with JRuby <= 9.2.5.0.
> Upgrade JRuby to 9.2.6.0

- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/converter/internal/ConverterProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/processorproxies/AbstractProcessorProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JavaConverterRegistryImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java
- asciidoctorj-distribution/build.gradle
- build.gradle
This PR upgrades Asciidoctor core to 2.0.0.
I also upgraded a few of the other gems after looking at the dependencies of Asciidoctor and what are the most current compatible versions.
For a release a new version of asciidoctor-diagram and asciidoctorj-diagram is required.
Once we have that I would like to release an AsciidoctorJ 1.7.0.
(I don't want to release a 2.0.0 yet given that there is still so much disagreement about how the API should look like in the future)
> Asciidoctor 2.0.0

- .travis.yml
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/log/internal/JavaLogger.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
- build.gradle
This PR implements the methods for the logger stub that were missing from its Ruby counterpart but which are called by Asciidoctor.
That way logging of invalid refs should work now without having to enable the $VERBOSE variable.
This change also appeared in https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/389
Additionally this PR upgrades Asciidoctor to 2.0.5 plus it should hopefully publish snapshot builds of master.
> Fix logger and upgrade to Asciidoctor 2.0.5

- README.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Cursor.java
- asciidoctorj-api/src/main/java/org/asciidoctor/log/LogRecord.java
I was creating my own logger, and I would have appreciated to find some Javadoc on the getters.
The text I wrote is based on what can be found in the README.adoc at the root of the repository.
> Logs handling API - add javadoc

- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
As proposed [here](https://github.com/asciidoctor/asciidoctorj/pull/795#issuecomment-483078104) `asciidoctorj --version` should show itself as AsciidoctorJ instead of AsciidoctorJRuby.
Apparently I got confused myself after the discussions about package names.
> Change AsciidoctorJRuby to AsciidoctorJ in version output

- README.adoc
- asciidoctorj-documentation/src/main/asciidoc/extension-migration-guide.adoc
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/TerminalCommandExtension.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/TerminalCommandTreeprocessorTest.java
- asciidoctorj-documentation/src/test/resources/extensionregistry/META-INF/services/org.asciidoctor.jruby.extension.spi.ExtensionRegistry
- docs/extension-migration-guide.adoc
- docs/integrator-guide.adoc
Other minor updates to the README.
This PR moves the documentation about the ExtensionRegistry to the Integrator Guide so that we are also able to test this documentation.
Additionally updated the current artifact version in the README and some other minor fixes.
> Moved docs about ExtensionRegistry to integrator guide with tests.

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/log/internal/JavaLogger.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
This PR fixes #790, where loggers were not configured when Asciidoctor was created simply with `Asciidoctor.Factory.create()`.
Additionally I squashed another bug where the logger proxy did not accept calls like `logger.info` with 0 arguments but a block yielding the message.
> Fix 790 register log handler

- asciidoctorj-api/src/main/java/org/asciidoctor/converter/AbstractConverter.java
- asciidoctorj-api/src/main/java/org/asciidoctor/log/Logging.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/converter/internal/ConverterProxy.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JavaConverterRegistryImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/TextConverter.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java
This PR is a proposal for adding logging support for converters.
If a converter implements the interface `org.asciidoctor.log.Logging`, then Asciidoctor will set a `org.asciidoctor.log.LogHandler` via `Logging.setLogHandler(logHandler)` after the converter was created.
The AbstractConverter already implements this interface and provides the method `log(LogRecord)` to log.
> Add logging support for converters

- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Block.java
Small copy paste issue in the Javadoc probably from `ListItem`.
> Fix javadoc in Block

- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenSourceHighlightingIsUsed.java
- build.gradle
This PR adds the rouge source highlighter to the asciidoctorj.jar.
There's also 2 tests checking that rouge and coderay work.
The distribution tests will also test that rouge still work in PDF, as we distribute a different version of rouge (2.0.7) in the asciidoctorj-pdf.jar.
> Add rouge source-highlighter to asciidoctorj.jar

- README.adoc
Resolves #802.
Clarify in the README that it is not sufficient to exclusively add asciidoctorj.jar to the class path to use it.
Clarify that versions of AsciidoctorJ and Asciidoctor no longer match.
> Clarify classpath in README

- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
hello i find a Code Quality Issue detected by SonarQube that Remove this useless assignment to local variable `equalsIndex`.
variable   `equalsIndex` will be assigned by `equalsIndex = attribute.indexOf(ATTRIBUTE_SEPARATOR)` , so the `int equalsIndex = -1` will be never used. so I change the condition to the assignment to fix the Code Quality Issue.
[https://rules.sonarsource.com/java/RSPEC-1854](url)
> remove useless assignment and change the if condition

- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
This has been done at JBCNConf 2019 Hackergarten with the help of @4lber10.
> Implement -R command-line option (#818)

- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedLongInlineMacroProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedRegexpInlineMacroProcessor.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/ManpageMacro.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- asciidoctorj-documentation/src/main/asciidoc/extension-migration-guide.adoc
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/ContextMenuInlineMacroProcessor.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/ImageInlineMacroProcessor.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/IssueInlineMacroProcessor.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/KeyboardInlineMacroProcessor.java
- docs/extension-migration-guide.adoc
- docs/integrator-guide.adoc
> InlineMacroProcessor must return a PhraseNode instead of a String

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
Fixes #808
This PR do not contains the version bump to `2.1.0`
> Add sourcemap, catalog_assets and parse to OptionBuilder

- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
Aligning with asciidoctor description of `:template_dir` (https://asciidoctor.org/docs/user-manual/#ruby-api-options) this PR marks `templareDir` method as deprecated pointing users to use `templateDirs` instead.
Additionally, fixes a couple of javadoc references in `Options`.
> marks templateDir in OptionsBuilder as deprecated

- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/log/internal/JULLogHandler.java
When using the log4j java util logger bridge handler, logs now show
`asciidoctor` instead of `unknown.jul.logger` for logger name.
fixes #833
> Include logger name for java util log handler

- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/AsciidoctorUtils.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java
> fix: do not merge command-line to string

- CHANGELOG.adoc
The issue can appear on any OS supporting white space in paths which
includes Linux and macOS.
> doc(changelog): #836 is not Windows-specific

- chocolatey/README.adoc
- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
Chocolatey offers a variety of JREs and JDKs but doesn't support alternate
dependencies[1]. Remove the jre8 dependency for now.
[1] https://github.com/chocolatey/choco/issues/879
> Chocolatey: Upgrade packaging to 2.1.0.

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java
- build.gradle
Fixed the semantic of the error message to reflect an error on the file
name instead of a missing file.
The unit test had issues:
* Test name was misleading as it was not testing the absence of input
file argument (which would trigger usage display) but the presence of
an empty input file name
* It was validating a bug in the parsing library fixed in JCommander
1.61 where empty arguments were lost - cbeust/jcommander#306
Fixes asciidoctor/asciidoctorj#782
> chore(CLI): ugprade to JCommander 1.72

- asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
Currently Asciidoctor instance can't be released.
With JRuby it means at least 2 pools are leaking each time an instance is created.
It leads to a lot of issues in several environments.
This PR adds a close() method to Asciidoctor and ensures JRuby instance is properly released when called.
Saved ~1mn on 1mn16s of execution with exec-maven-plugin for instance and avoids leakage in EE context.
> adding close to Asciidoctor to avoid to leak when creating an asciidoctor instance

- README.adoc
* update the JRuby dependency (this is required to make it work with WildFly 17.0.1, and matches the JRuby version that the current v2.1.0 depends upon)
* rename "WildFly AS" to just "WildFly"
> Update section about running on WildFly

- build.gradle
When investigating issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/337 I found that the latest ruby version fixes some assertions, see https://github.com/jruby/jruby/pull/5693.
As the test suite of AsciidoctorJ runs without errors on this new JRuby release, I suggest an update of JRuby with this PR.
> upgrade jruby to 9.2.8.0 as it fixed some assertions bugs

- README.adoc
This is a documentation-only update.
Added tarball links to the Distribution section.
Added a Quick Win section so users could get started straight away with doing a conversion, whether that's the end goal, or to get an idea of how the results would look after integrating the API.
> Documentation: link to tarball; add Quick Win section

- asciidoctorj-api/build.gradle
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/package-info.java
- asciidoctorj-api/src/main/java/org/asciidoctor/converter/package-info.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/package-info.java
- asciidoctorj-api/src/main/java/org/asciidoctor/log/package-info.java
- asciidoctorj-api/src/main/java/org/asciidoctor/package-info.java
- asciidoctorj-api/src/main/java/org/asciidoctor/syntaxhighlighter/package-info.java
- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/package-info.java
- build.gradle
- Native Gradle OSGi integration is deprecated in Gradle 5.x
https://docs.gradle.org/5.0/release-notes.html#deprecated-osgi-plugin
- Use OSGi annotations to lower manifest synchronization cost
https://bnd.bndtools.org/chapters/230-manifest-annotations.html
- Adjusted `Export-Package` for asciidoctorj-api:
- `org.asciidoctor.spi` removed as it seems an overlook of bc753140206
- added `org.asciidoctor.syntaxhighlighter` as generation was
reporting the following warning:
`warning: Export org.asciidoctor,  has 1,  private references [org.asciidoctor.syntaxhighlighter]`
(may have been an overlook of 3e9d47e73)
On a side note, the Bundle-SymbolicName conflict reported at #772 still
exists.
> chore(OSGi): switch to biz.aQute.bnd plugin

- asciidoctorj-distribution/build.gradle
WARNING: since the Groovy Gradle API is modified, this breaks build
isolation when sharing a common Gradle daemon instance.
This hack works because gradle-bintray-plugin is using Groovy dynamic
compilation (i.e. compiled in Groovy without @CompileStatic) hence it is
affected by Groovy runtime meta-programming.
Tested with: Gradle 5.6.3 / gradle-bintray-plugin 1.8.4
asciidoctor/asciidoctorj#861
bintray/gradle-bintray-plugin#300
> fix: hack for Gradle 5 + signed artifacts + gradle-bintray-plugin 1.8.4

- .github/workflows/continuous-integration.yaml
- test-asciidoctor-upstream.sh
This PR adds CI builds using Github Actions.
Right now it runs a build on master on push to master and every day at 9AM UTC.
PRs are also built.
In the beginning we can keep this in parallel to the build on TravisCI until we are confident that Github works as we need it.
Open points:
- Github Actions also supports building on Windows, I plan to add this later
- I have to look up how to implement the trigger that we currently use for the asciidoctor upstream build. Until we have that we have the scheduled daily build though which should also capture changes, even though it is of course not easy to track down the breaking changes if there were multiple commits to Asciidoctor within a day.
> Run CI build using Github Actions

- .github/workflows/continuous-integration.yaml
Accidentally skipped tests in Github Actions.
This PR adds them again.
I had them removed initially for quicker turnaround times when testing the upstream build.
> Don't skip tests in CI build

- README.adoc
Reverts asciidoctor/asciidoctorj#870
Apparently it was correct, but showed "not available" for some other reason.
Not sure I am a fan of query params :D
> Revert "Fix badge URL"

- .github/workflows/continuous-integration.yaml
[ ] Bug fix
[X] Build improvement
Run the CI builds on Windows on GH actions.
Add the respective build config.
No
No
> Build on Windows

- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/IOUtils.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java
[X] Bug fix
This PR builds on the awesome changes from @nicerloop in #864 
On top of that I added a few fixes where that PR deviated from the behaviour in asciidoctor:
`echo "Hello World"|asciidoctorj -` will create a full document including header and footer, just like asciidoctor does.
`echo "Hello World"|asciidoctorj - -b pdf` writes the pdf document to stdout.
In addition to the changes in #864 this PR by default sets the option `:standalone` to `true`, that's also what the Asciidoctor CLI does [here](https://github.com/asciidoctor/asciidoctor/blob/4155916105b3276e5971349b1730b9d095d29db3/lib/asciidoctor/cli/options.rb#L15).
If the cli argument `-s/--no-header-footer` is passed, …
> Fix reading input from stdin and writing to stdout

- .github/workflows/upstream-build.yaml
[ ] Bug fix
[x] Build improvement
This PR adds a build trigger for the upstream build, so that asciidoctor/asciidoctor can trigger upstream builds on every commit, similar to what we have today with travis.
Registers a workflow that is triggered on `repository_dispatch`.
An upstream build can be triggered like this now:
```
curl -XPOST https://api.github.com/repos/asciidoctor/asciidoctorj/dispatches \
-H 'Accept: application/vnd.github.everest-preview+json' \
-H 'authorization: token <token>' \
-H 'content-type: application/json' \
--data '{
"event_type":"test_upstream", 
"client_payload": {
"message":"Triggered by commit xyz", 
"branch": "master" …
```
> Add upstream build trigger

- CHANGELOG.adoc
- asciidoctorj-api/build.gradle
- asciidoctorj-core/build.gradle
[X] Bug fix
This PR associates distinct Symbolic-BundleNames to the archives asciidoctorj-api.jar and asciidoctorj.jar.
These names now reflect the Maven coordinates, i.e. `org.asciidoctor.asciidoctorj-api` and `org.asciidoctor.asciidoctorj`.
> Fix 878 osgi symbolicname

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
- build.gradle
- gradle.properties
Apparently the torquebox Maven proxy does not work anymore.
That means that all builds currently fail because gems cannot be downloaded.
This PR tries to circumvent the problem by using the functionality of the ruby-gradle-plugin to start an internal server that runs the torquebox proxy servlet.
> Remove torquebox proxy

- README.adoc
[ ] Bug fix
[X] Documentation update
Updates artifact versions in README to last published versions:
* core: 2.2.0,
* epub3: 1.5.0-alpha.9
* pdf 1.5.0-beta.8
. jruby 9.2.9.0
Updates README with updated versions of artifacts & jruby.
Also:
* Defines new property `asciidoctorj-epub3-version` and uses it where before there was a constant.
* Fixes missing colon in `jruby-version` property.
_No_
_No_
Fixes #Issue 
_Not applicable_
Please add a corresponding entry to the …
> update artifact versions in README

- CHANGELOG.adoc
- asciidoctorj-core/build.gradle
- build.gradle
[ ] Bug fix
[X] Build improvement
Upgrade the jruby-gradle-plugin to end the fiasco around the torquebox proxy and different Java version.
I checked manually that the table of contents of the asciidoctorj-2.2.0.jar is the same as the toc from the jar built with this PR.
> Upgrade JRuby plugin to 2.0.0-alpha.7

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.adoc
- README.adoc
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/AsciidoctorInterface.java
- docs/integrator-guide.adoc
The documentation was not updated to reflect how to create an Asciidoctor instance with a GEM_PATH.
This PR updates the docs to show that.
Also added a hint that Asciidoctor implements AutoCloseable.
> Fix #890. Show how to create an Asciidoctor instance with GEM_PATH

- CHANGELOG.adoc
- README.adoc
_Makes documentation clearer highlighting admonitions with icons. At least for me_
_Same icons used as in https://github.com/asciidoctor/asciidoctor/blob/master/README.adoc_
_Uses github special tags as attributes_
_Not that I know_
_No_
Fixes #Issue 
> adds support for github admonitions icons

- chocolatey/README.adoc
- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
Upgrade the Chocolatey packaging assets for AsciidoctorJ version 2.2.0
Bumps version numbers and the SHA256 sum.
The Chocolatey package page is at https://chocolatey.org/packages/asciidoctorj/
> Chocolatey: Upgrade packaging to 2.2.0.

- CHANGELOG.adoc
- README.adoc
- build.gradle
Upgrade AsciidoctorJ-epub3 to the latest and greatest 1.5.0-alpha.16
> Update asciidoctorj-epub3 to v1.5.0-alpha.16

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/BaseProcessor.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Contexts.java
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Processor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/internal/JRubyProcessor.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/ListCreatorBlockMacro.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockMacroProcessorCreatesAList.groovy
- config/codenarc/codenarc.groovy
As @glisicivan identified in #916 that the Extension API is currently missing methods to create Lists.
This PR adds the missing methods.
The PR adds the following method to `Processor` and a few overrides if no attributes or options are used:
```java
org.asciidoctor.ast.List createList(StructuralNode parent, 
String context, 
Map<String, Object> attributes, 
Map<Object, Object> options);
```
To create an ordered list `"olist"` must be passed as the context parameter.
For unordered lists `"ulist"` must be passed.
That means to create an ordered list simply call this from within an extension:
```java
var list = createList(parent, "list");
```
An alternative might have been to define methods like …
> Fixes #916. Add factory methods to create lists

- CHANGELOG.adoc
- build.gradle
upgrade rouge to prevent exception about uninitialized constant Rouge::Lexers. See https://github.com/asciidoctor/asciidoctorj/issues/925 and https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/505 for a discussion where this happens.
When I build this new version of AsciidoctorJ and test it in my local setup (AsciiDoc plugin for IntelliJ), this change fixes the error. 
What is strange for me: the test WhenSourceHighlightingIsUsed#should_render_with_rouge worked before and after the change. I wasn't able to provide a test that fails before the upgrade and succeeds after the upgrade.
I am looking forward to a bugfix release to use it in the AsciiDoc plugin for IntelliJ. 
Fix error when using Rouge highlighter when creating HTML
How does …
> upgrade rouge to prevent exception (fixes #925)

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyHashMapDecorator.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenTheInlineMacroProcessorRunsTwice.java
This is a fix for #926.
The problem here is that symbols in the extension config currently are converted to strings and then change the behaviour if an extension is used multiple times.
Probably, the whole mapping of Symbols and Strings between Ruby and Java is quite complex if Symbols should appear as Strings in the Java space, but have to remain Symbols in the Ruby space, but I couldn't figure out a cleaner way yet.
If somebody uses the extension config and …
> Fixes #926. Make sure that symbols stay symbols in extension config.

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/StructuralNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyObjectWrapper.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/LevelConverter.java
- asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java
This PR adds the missing method to set the level of a structural node (`StructuralNode.setLevel(int)`)
Fixes #931 
> Fixes #931. Add method StructuralNode.setLevel()

- CHANGELOG.adoc
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/HighlightJsExtension.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/HighlightJsHighlighter.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/WhenAHighlightjsAdapterIsImplementedInGroovy.groovy
Fix the upstream build
The test for simulating the HighlightJS syntax highlighter in Java/Groovy was failing due to changes in the Ruby original.
This PR changes the test to simulate both behaviours and expect one of them.
> Fix upstream test to adapt to changes in HighlightJS syntax highlighter.

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/log/internal/JavaLogger.java
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenBackendIsPdf.java
- asciidoctorj-distribution/src/test/resources/empty-table.adoc
Fixes #944.
The goal of this pull request is to fix the issue #944 
When I convert the following asciidoctor file with Asciidoctorj 2.3 (or 2.4) and the pdf backend:
```asciidoctor
=== Empty table
|===
|===
```
Asciidoctorj fail with the following NullPointerException stacktrace:
```console
java.lang.NullPointerException
at org.asciidoctor.jruby.internal.RubyObjectWrapper.<init>(RubyObjectWrapper.java:23)
at org.asciidoctor.jruby.ast.impl.CursorImpl.<init>(CursorImpl.java:10)
at org.asciidoctor.jruby.log.internal.JavaLogger.getSourceLocation(JavaLogger.java:209)
at org.asciidoctor.jruby.log.internal.JavaLogger.log(JavaLogger.java:152)
at …
```
> Fix NPE when a document contains an empty table

- CHANGELOG.adoc
- asciidoctor-gem-installer.pom
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/HighlightJsHighlighter.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/WhenAHighlightjsAdapterIsImplementedInGroovy.groovy
Fix https://github.com/asciidoctor/asciidoctorj/issues/953 by making the test do not depend on Asciidoctor highlight.js version.
Test each file against the version used in each SyntaxHighlighterAdapter, and then test against real Asciidoctor but striping the version numbers,
Maybe test don't need to match agains a real Asciidoctor conversion?
No.
Fixes #Issue 
Please add a corresponding entry to the …
> closes #953: make SyntaxHighlighter test independent from highlight.js version

- asciidoctorj-documentation/build.gradle
Please see #963
Fixes #963 
I don't think this deserves a  CHANGELOG entry, but lemme know.
> Generate docs when associated Java source is changed

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Catalog.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Document.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Footnote.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/CatalogImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DocumentImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/FootnoteImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyHashMapDecorator.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/converter/CatalogOfRefsAreAvailable.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/converter/WhenFootnotesAreUsed.groovy
- asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
- docs/integrator-guide.adoc
Adds AST access to document footnotes and refs so that a converter may refer to them.
Access is provided under `Document` via:
- `getCatalog()`
- `getFootnotes()`
- `getRefs()`
Fixes #958
CHANGELOG has been updated accordingly.
> AST now provides access to document catalog footnotes and refs

- asciidoctorj-core/src/test/java/org/asciidoctor/extension/SayMacro.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
If you want that to apply the substitutions in an Inline macro, you need to use following attribute:
* `key`: `"subs"`
* `value`: `":normal"`
See this [StackOverflow question](https://stackoverflow.com/questions/65017746/how-to-have-the-returned-inline-being-formatted-in-an-asciidoctorj-inlinemacropr) and the related discussion with @mojavelinux on [twitter](https://twitter.com/mojavelinux/status/1331935753593491456).
This PR adds a test case to ensure this approach is working (as guaranty there will be no regression in the future).
This correspond to this reference test in the ruby asciidoctor project:
https://github.com/asciidoctor/asciidoctor/blob/master/test/extensions_test.rb#L1415-L1431
On the long term, some convenience could be added to the attribute builder to set substitutions.
> Add test case with inlineMacro with substitutions

- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
To enable support for toclevels attribute, which defines how many levels should be displayed in the toc
By adding the constant and the setter for this functionality
I guess not
No
Added support of `toclevels` attribute
> Added support of toclevels attribute

- .github/workflows/upstream-build.yaml
- CHANGELOG.adoc
- asciidoctorj-api/build.gradle
- asciidoctorj-arquillian-extension/build.gradle
- asciidoctorj-core/build.gradle
- asciidoctorj-distribution/build.gradle
- asciidoctorj-test-support/build.gradle
- gradle.properties
- gradle/publish.gradle
This PR hopefully completely fixes the publishing to Maven Central.
With these changes I have published AsciidoctorJ 2.4.3 to a staging repository, that means it is not really published yet, but can be tested by everyone first.
To use this version add the following repository to your Maven config (every publish gets its own repo):
```xml
<repositories>
<repository>
<id>staging</id>
<url>https://oss.sonatype.org/content/repositories/orgasciidoctor-1240</url>
<releases>
<enabled>true</enabled>
</releases>
</repository>
</repositories>
```
Before merging it would be great if somebody else could also check this. 
One point where I need help is in asciidoctorj-distribution/build.gradle.
In that file the build has to add the result of the distZip task to the publication configured in the …
> Release 2.4.3

- CHANGELOG.adoc
- build.gradle
Upgrade the gradle plugin to create the OSGi manifests to the latest version 5.2.0 and get rid of the last dependency on jcenter.
Fixes #Issue 
> Upgrade OSGi plugin biz.aQute.bnd to 5.2.0

- asciidoctorj-documentation/build.gradle
One of the tests relies on Nashorn, which is not supported anymore with Java 15+.
This PR fixes that.
It entirely excludes the test from compilation.
Include Nashorn as an external dependency and use it on the module path.
Fixes #Issue 
> Exclude test relying on Nashorn from Java 15+

- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
Switch the download URL to search.maven.org.
Upgrade the Chocolatey packaging to 2.4.3, including switching the download URL to Maven Central.
> Chocolatey: Upgrade packaging to 2.4.3.

- asciidoctorj-wildfly-integration-test/build.gradle
- asciidoctorj-wildfly-integration-test/src/test/resources/arquillian.xml
Run `asciidoctorj-wildfly-integration-test` with Java16
The fix only requires upgrading dependencies to latests
```
arquillianVersion = '1.6.0.Final'
arquillianWildflyVersion = '3.0.1.Final'
```
And addind the repo `https://maven.repository.redhat.com/ga/`, without it, build fails unable to collect certan specific dependencies.
Tried different version to see if the extra maven repo could be removed without much luck. A part form that, not much alternatives to test.
Are there any implications of this pull request? Anything a user must …
> Run Wildfly IT with Java16

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Document.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/AuthorImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DocumentHeaderImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DocumentImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
Expose authors information through `Author` class from Document instance.
This allows to easily obtain such information without having to parse author, and email attributes.
Full discussion https://github.com/asciidoctor/asciidoctorj/issues/970.
Adds `List<Author> getAuthors()` to Document interface and DocumentImpl implementation.
In order to avoid internals, this implementation does not use attributes but uses the `authors` property and `Author` struct of the Ruby implementation. This allows for simple code since it's not necessary to reimplement the attributes parsing logic in Ruby. …
> Expose author as class from Document

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Document.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/DocumentHeader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DocumentImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
Expose RevisionInfo from Document to be accessible from extensions.
Note this is different from how the info is exposed in Asciidoctor Ruby, but aligned with Asciidoctor.js.
Adds `RevisionInfo getRevisionInfo()` to `Document` interface.
Uses same implementation found in `DocumentHeaderImpl`.
:point_right: Only thing to discuss is we want to deprecate the Header methods in this same PR or do it separatedly. :point_left: 
Other than that, the PR is harmless.
No. …
> Expose RevisionInfo from Document interface

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/AttributesBuilder.java
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/OptionsTest.java
- docs/modules/ROOT/examples/org/asciidoctor/integrationguide/OptionsTest.java
- docs/modules/ROOT/pages/asciidoctor-api-options.adoc
- docs/modules/ROOT/pages/asciidoctor-interface.adoc
- docs/modules/ROOT/pages/conversion-examples.adoc
- docs/modules/ROOT/pages/convert-to-epub3.adoc
- docs/modules/ROOT/pages/ruby-extensions.adoc
- docs/modules/ROOT/pages/safe-mode-and-filesystem-access.adoc
- docs/modules/ROOT/pages/write-converter.adoc
- docs/modules/extensions/pages/docinfo-processor.adoc
- docs/modules/guides/pages/extension-migration-guide-15-to-16.adoc
Make compatible changes to guide users for future changes
Make the experience interacting with Asciidoctor API simpler and less confusing, while mantaining compatibility with current methods and types.
Marks non-prefered methods as deprecated, so users can strt applying changes.
In terms of making the changes smooth no.
No
Related to #977  but does not close it completely.
Please add a corresponding …
> Simplify Options and Attributes creation

- asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
- docs/modules/ROOT/pages/read-document-tree.adoc
Add missing `load` and `loadFile` using `Options` and deprecate the other.
Plus, update docs.
really? :roll_eyes: 
No
no
Fixes #Issue 
Related to https://github.com/asciidoctor/asciidoctorj/issues/977
> Add load(String,Options) and loadFile(File,Options)

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/PreprocessorReader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/internal/PreprocessorReaderImpl.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/LsIncludeProcessor.java
Rename `PreprocessorReader::push_include` to `pushInclude` to align with Java conventions.
Also deprecates the old method to keep this change compatible.
-
no
Fixes #980
> Rename push_include to pushInclude

- docs/modules/guides/pages/use-prerelease-version.adoc
Fix an invalid title that causes the filename to appear in the menu
Fix title level from 2 to 1.
:thinking: 
No, that I know of.
Fixes #Issue 
> Fix doc filename instead of title shown in nav menu

- CHANGELOG.adoc
- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenADocumentContainsADefinitionList.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenSubstitutionsAreUsed.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/ConfigModifyingBlockProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/GithubContributorsBlockMacro.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/TableCreatorTreeProcessor.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorSetsTheSourceMapOption.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenExtensionsAreRegisteredAsService.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/WhenASyntaxHighlighterIsRegistered.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/syntaxhighlighter/WhenASyntaxHighlighterThatWritesStylesheetsIsRegistered.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/syntaxhighlighter/HighlightJsHighlighterTest.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/syntaxhighlighter/OrderTest.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/syntaxhighlighter/PrismJsHighlighterTest.java
- asciidoctorj-wildfly-integration-test/build.gradle
- build.gradle
- docs/modules/ROOT/examples/org/asciidoctor/integrationguide/OptionsTest.java
- docs/modules/syntax-highlighting/examples/org/asciidoctor/integrationguide/syntaxhighlighter/HighlightJsHighlighterTest.java
- docs/modules/syntax-highlighting/examples/org/asciidoctor/integrationguide/syntaxhighlighter/PrismJsHighlighterTest.java
This PR upgrades the test dependencies on Spock and Arquillian, so that the wildfly test no longer uses a different version of Arquillian than the rest of the project.
I had to disable Arquillian for 2 of the Spock tests that use Data Tables. If I haven't done any mistake I assume that there is some bug in there and I'll open a ticket for arquillian-spock at the next occasion.
The upgrade of the codenarc plugin also required some changes in some test.
> Upgrade test dependencies on Arquillian and Spock

- CHANGELOG.adoc
- build.gradle
The upgrade of concurrent-ruby to 1.1.8 in AsciidoctorJ 2.5.0 resulted in the initialisation of asciidoctor-pdf taking an additional ~10 seconds.
This PR reduces that again to the previous time taken.
Downgrade concurrent-ruby to 1.1.7 which doesn't seem to expose this behavior.
Not from AsciidoctorJ's point of view.
Fixes #Issue 
> Fixes #1032. Downgrade concurrent-ruby to 1.1.7

- CHANGELOG.adoc
- asciidoctorj-test-support/build.gradle
Sonatype sent a warning that we are still relying on unit 4.12 which has an open CVE.
Indeed asciidoctorj-test-support still has that dependency even though the build itself should already have used the fixed version 4.13.2.
This PR  upgrades this last remaining dependency to 4.13.2 too to avoid that CVE.
Fixes #Issue 
> Upgrade remaining dependency on junit 4.12 to 4.13.2

- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
Upgrade version of Spring Boot version used in the Spring Boot integration test.
Simply upgrade the configuration of the submodule `springboot-app`.
It also removes an unnecessary asciidoctorj version property.
If necessary we could consider parameterizing the version in a way that allowed to run the same test against several version, por example the 2 most recent minnors. But that can be tricky when we fund breaking changes between minors.
No.
If this PR fixes …
> Bump SpringBoot version to latest 2.5.2 in it test

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java
- build.gradle
* Bump jCommander version to latest v1.81
* Modernize CLI related classes:
* Fix deprecated calls
* User Java8+ structs when (opinionably) applicable
* Applied default IntelliJ Formatting
Test pass and I have not gone far in code changes just in case.
Fixes #Issue 
> Modernize cli

- docs/modules/ROOT/pages/logs-handling.adoc
The custom LogHandle given as an example in the Logs Handling API sections didn't work, as it used 'extends' rather than 'implements' to the LogHandler interface.
Fix an error on the code given in the Logs Handling API documentation section
Code snippet updated (extends replaced with 'implements')
N/A 
N/A
Fixes #Issue 
> Fix example on Logs Handling API documentation

- CHANGELOG.adoc
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenExtensionsAreRegisteredAsService.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- build.gradle
This PR upgrades Asciidoctor to the latest and greatest version 2.0.17.
I also updated JRuby to 9.2.20.1.
I tried to upgrade it to 9.3, however the build failed with OOM errors in `org.jruby.util.ByteList#ByteList(int)`. I need to check if this is due to building on ARM64 or if it also reproduces on Intel.
> Upgrade to asciidoctor 2.0.17

- asciidoctorj-wildfly-integration-test/build.gradle
There is a warning in the build: 
> 2022-01-07T17:47:08.9908240Z > Task :asciidoctorj-wildfly-integration-test:unpackWildfly
2022-01-07T17:47:08.9910154Z Execution optimizations have been disabled for task ':asciidoctorj-wildfly-integration-test:unpackWildfly' to ensure correctness due to the following reasons:
2022-01-07T17:47:08.9914578Z   - Gradle detected a problem with the following location: '/home/runner/work/asciidoctorj/asciidoctorj/asciidoctorj-wildfly-integration-test/build'. Reason: Task ':asciidoctorj-wildfly-integration-test:compileTestJava' uses this output of task …
> add explicit dependency after Gradle complained

- CHANGELOG.adoc
- asciidoctorj-distribution/build.gradle
- asciidoctorj-wildfly-integration-test/build.gradle
- build.gradle
- gradle/versioncheck.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrade to the latest version of jcommander.
Upgrade to the latest version of Gradle and some cleanup of the build scripts that Gradle complained about.
> Upgrade to jcommander 1.81 and gradle 7.3.3

- CHANGELOG.adoc
- asciidoctorj-springboot-integration-test/build.gradle
- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
- asciidoctorj-wildfly-integration-test/build.gradle
- asciidoctorj-wildfly-integration-test/src/test/resources/arquillian.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Gradle
- JRuby
- Wildfly for integration test
- Spring Boot for integration test
This PR updates the versions of several dependencies. That's it.
> Update versions of Gradle, JRuby and frameworks for integration tests.

- CHANGELOG.adoc
- asciidoctorj-core/build.gradle
- build.gradle
- gradle/eclipse.gradle
- gradle/versioncheck.gradle
The versionCheck task does not work properly right now since it compared the version of the last gem to the project version.
Since the versions of AsciidoctorJ no longer align with the version of the Asciidoctor gem and generally have higher numbers now, this task never identifies an outdated version.
This is fixed by looking up the resolved dependency and its version number.
Additionally I made a minor change to the build script to apply the jruby gradle plugin only to the main AsciidoctorJ module and not to all modules anymore.
> Fix version check

- .github/workflows/release.yaml
- CHANGELOG.adoc
Build releases on Github actions.
The PR has a new workflow for building releases.
I configured secrets for the signing key and the access token for Sonatype.
For now the idea for this to work is:
1. We update main so that it has a release version
2. We trigger the action manually on github.com or via CLI
3. GH runs a full build and publishes to a Sonatype staging repository and closes it
Going forward I'd like to switch to the way asciidoctor/asciidoctor does it by simply pushing a tag.
Yes, for example build and publish release on …
> Add Github Actions workflow for building and publishing releases

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Cell.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/CellImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
Fix the issue #1096.
Calling Document.findBy() should not result in a ClassCastException.
Make Cell extend StructuralNode instead of ContentNode. That way the ClassCastException does not happen anymore since `Document.findBy()` returns a `List<StructuralNode>`
Make `Document.findBy()` return a `List<ContentNode>`. However, afaict, this doesn't make much sense.
No.
It's currently on the main branch which eventually results in the next major version. 
However, …
> Fixes #1096. Make Cell extend StructuralNode instead of ContentNode.

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Cell.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/CellImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsLoadedToDocument.java
- gradle.properties
Similar to #1099 this PR makes org.asciidoctor.ast.Cell extend StructuralNode instead of ContentNode.
This matches also the class hierarchy in Asciidoctor Ruby.
That way, if Document.findBy() returns a Cell in the result list there will no longer be a ClassCastException.
Probably.
I'd like to argue that this is an almost fully compatible change that doesn't even break binary compatibility: https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html
Someone …
> v2.5.x: Fixes #1096. Make Cell extend StructuralNode instead of ContentNode.

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/MaxSeverityLogHandler.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/SeverityConverter.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java
The Ruby asciidoc CLI has option --failure-level which forces the CLI to exit with non-zero status code if the specified logging level (severity) is reached. See: https://github.com/asciidoctor/asciidoctor/pull/2674, https://github.com/asciidoctor/asciidoctor/issues/2003, https://github.com/asciidoctor/asciidoctor/issues/854
This PR implements the same functionality for AsciidoctorJ, pretty much the same way as the Ruby code (keeps track of highest seen log message severity, and checks that the end).
The default value is the same as in Ruby - only "fatal" severity causes non-zero exit code - which probably won't break many things (but someone running AsciidoctorJ as part of a CI build would probably want to fail on "error" severity as well, maybe even "warn"). 
Fixes #1113
> Add --failure-level command line option to force non-zero exit code (fixes #1113)

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
- ci/test-asciidoctor-upstream.sh
Fix upstream tests.
Force "-SNAPSHOT" suffix to upstream version
to install gem consistently.
gem-maven-plugin appends it when the gem version
is not strictly semver installing a gem with "-SNAPSHOT"
in the version but not in the maven repo path.
Tried a few things as mentioned here https://github.com/asciidoctor/asciidoctorj/pull/1121#issuecomment-1273907410, option 3 did not work in CI, and this seemed to me the more consistent. We get the sama version format and install path always.
I don't discard spending some extra time with …
> Fix upstream test

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Section.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/SectionImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/SectionImplTest.java
Exposes [sectnum](https://github.com/asciidoctor/asciidoctor/blob/4bab183b9f3fad538f86071b2106f3b8185d3832/lib/asciidoctor/section.rb#L119) to users using the API for extensions, converters, etc.
This property is required to easily obtain the section numbering aligned with other Asciidoctor attributes. The alternative is reimplementing all the logic of level counting, secnumlevel, separators formating, etc.
Adds 2 new methods:
* `String getSectnum()`
* `String getSectnum(String delimiter)`
to the Section interface, those simply call the Asciidoctor Ruby property (I assume property is …
> Expose Section's sectnum property

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/AttributesBuilder.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java
Replace use of deprecated attribute `numbered` by recommended value `sectnums`.
* Replaces constant https://github.com/asciidoctor/asciidoctorj/blob/2a57067e4ab64cc149d64d6a0c98913f1eba914f/asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java#L41
* Updates tests and JavaDocs when necessary
* No extra tests have been added. There are already valid ones present.
No
Only for users comparing the attibute with the internal value will notice. I personally …
> Replace use of deprecated 'numbered' attribute by 'sectnums'

- CHANGELOG.adoc
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
- build.gradle
Upgrade Asciidoctor core to the latest version 2.0.18 for the AsciidoctorJ 2.5.x branch
> Upgrade to Asciidoctor 2.0.18

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/AttributesBuilder.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java
This PR cherry picks #1124 into the v2.5.x branch.
> Issue 1120 replace deprecated numbered by sectnums v2.5.x

- CHANGELOG.adoc
- ci/asciidoctor-gem-installer.pom
The upstream build is currently broken.
This PR tries to fix it again.
The current configuration tries to fetch the jruby maven plugin from https://rubygems-proxy.torquebox.org/releases. This seems to be hosting some Russian gambling site now 🤪
However, it should be possible to download this plugin simply from Maven central.
Therefore, this PR removes the configuration of the plugin repository.
Fixes …
> Fix upstream build.

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Document.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DocumentImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyObjectWrapper.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/SectionImplTest.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/WhenDocumentIsLoaded.java
Expose Document's `source` and `source_lines` properties.
This is required to be able to use other asciidoctor components like [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer).
Using already present AsciidoctorJ APIs and practices, nothing special.
Not that I know.
No
Fixes #1143 
> Expose Document's source and source_lines properties

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
- asciidoctorj-core/build.gradle
- asciidoctorj-springboot-integration-test/build.gradle
- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
- build.gradle
- docs/modules/ROOT/pages/logs-handling.adoc
- gradle/wrapper/gradle-wrapper.properties
Remove support for Java 8 and set 11 as de minimal version.
Java8 is EOL and I don't think we should promote using it.
* Remove use of 'task.options.release' for Java version configuration in favour of Gradle's preferrs 'toolchain'.
* Removed Java 8 from pipelines.
Also:
* Bump Gradle to latest v8.0.2
* Remove use of 'io.spring.dependency-management' Gradle plugin in 'spring-boot' app in favor of Gradle's BOM support. This reduces maintenance since only Boot version needs to be updated.
* Enables CI pipelines for Java 19 on macos and Windows.
`task.options.release` still works, but Gradle docs suggest using the new toolchain configuration as this is the …
> Set Java11 as minimal version

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
Fix the option to set toDir internally.
Deprecate the option to warn users it is being [removed in v3.0.x](https://github.com/asciidoctor/asciidoctorj/pull/1153).
Set toDir and add deprecation documentation.
No
No
Fixes #853
Fixes #941
> Deprecate destinationDir option for v2.5.x

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/AsciidoctorUtils.java
Fix the issue where using the option `destinationDir` from API had no effect.
The option only is used for the CLI, in that case the value is redirected to 'to_dir'.
1. Completely removes the option from `OptionsBuilder` and `Options` class.
2. Moves the constant with the name from `Options` to `AsciidoctorUtils`: this is the second time I struggle with this class. It's out of place because it contains CLI elements to build the asciidoctor command for logging purposes in the core. So to prevent cyclic dependencies some constants are copied both here and in the `asciidoctor-cli` sub-module -> Solution = create new sub-module "shared" or remove the logging. Third time will be the charm :thinking: 
Are there any alternative ways …
> Remove invalid destinationDir option from API for v3.0.x

- CHANGELOG.adoc
- asciidoctorj-distribution/build.gradle
Remove `WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem` message at least when running the CLI.
Simply adds required `--add-open`  options.
No.
This is not related to  https://github.com/asciidoctor/asciidoctorj/issues/1034, and does not fix it.
Fixes #1155
> Add required '--add-opens' to cli script

- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Section.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/SectionImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyObjectWrapper.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/SectionImplTest.java
Mainly provide some closure to issue #1122.
Test Section.isNumbered to ensure expected behavior
* Core 'numbered' property is not always boolean. In those cases, the boolean can be coerced from non-null value.
See https://github.com/asciidoctor/asciidoctorj/issues/1122
* Minor improvements to RubyObjectWrapper.
We could make further tests and check if the property has the ':chapter' object. But the current implementation already meets the tests, so I see no point in complicating it.
Also, it does not tests doctype `manpage` and `inline` since in those the sections are not taken into consideration or cannot be numbered (manpage).
For reference, I left a comment pointing to the …
> Test Section.isNumbered to ensure expected behaviour

- CHANGELOG.adoc
- asciidoctorj-distribution/src/main/resources/customUnixStartScript.txt
Remove `Native subprocess...` warning when running the CLI in Java > 8.
```
023-04-01T22:03:19.247+02:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
```
Modifies CLI script to check the Java version running, in case of Java >8 adds required arguments to remove warning.
Leave the warning and document it. However, given the majority of users should be on Java > 8, leaving the warning because we still support it, seems unfair and lazy.
The script …
> (v2.5.x) Remove open access warnings from cli

- .github/workflows/continuous-integration.yaml
Fix pipelines not running on PR on branch v2.5.x
Pretty obvious fix in the configuration :sweat_smile: 
GH reads from the PR file, not the on main `branch`. I'll reuse the open PR on main to remove 2.5 from that.
No
No
Fixes #Issue 
Not worth mentioning I think.
> Enable GH actions on branch 2.5.x

- build.gradle
It repairs error with parsing PlantUML with awslib,
It could not include <awslib/Groups/all>
Updates asciidoctorj-diagram-plantuml to 1.2022.14, which repairs 'cannot include <awslib/Groups/all>' in PlantUML
> Updates DiagramPlantumlVersion to 1.2022.14

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/AsciidoctorUtils.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenSourceHighlightingIsUsed.java
- asciidoctorj-core/src/test/java/org/asciidoctor/util/TestHttpServer.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/OptionsTest.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/YellBlockProcessorTest.java
- asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/syntaxhighlighter/HighlightJsHighlighterTest.java
- docs/modules/ROOT/pages/asciidoctor-api-options.adoc
Deprecate 'headerFooter' in favour of 'standalone'
* Replace headerFooter methods in OptionsBuild & Options
* Added 'standalone' description to docs
Other changes included:
* Re-ordered options in docs to follow alphabetical order
* Remove some unnecessary throws from tests
* Add missing '@deprecated' to templateDir method
Related to https://github.com/asciidoctor/asciidoctorj/pull/1161
Simply add new method and change the use of the header_footer option in the internal map by standalone.
The old option is still accepted in the map, hence the check in `AsciidoctorUtils`.
No
No, no breaking change …
> (v2.5.x) Deprecate 'headerFooter' in favour of 'standalone'

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Catalog.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/ImageReference.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/CatalogImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/FootnoteImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ImageReferenceImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyGemsPreloader.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenTwoAsciidoctorInstancesAreCreated.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/converter/WhenFootnotesAreUsed.groovy
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenReaderIsManipulatedInExtension.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/TestImageReference.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/internal/WhenReadingImagesFromCatalogAsset.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/internal/WhenReadingImagesFromCatalogAssetFromConverter.java
- asciidoctorj-core/src/test/resources/sample-with-images.adoc
**DRAFT PR, WIP**
Offer users the option to obtain images from the assets catalog.
**However**, it only works when calling `load()+getContent()`, and unlike in Asciidoctor Ruby, we cannot call `convert` because it fails (see [comment](https://github.com/asciidoctor/asciidoctorj/issues/1166#issuecomment-1500921789)).
Exposes the images properties from the catalog.
However, this PR is not done yet untill:
WIP
Not
Fixes #1166 
> Retrieve all images in catalog during conversion

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyOutputStreamWrapper.java
Fix the issue reported in #1158.
When converting to a stream a new RubyClass is created lazily.
This step is not protected with a mutex, so that JRuby can fail.
This PR wants to fix this so that this exception does not occur when converting documents in parallel with one Asciidoctor instance.
Eagerly create the class when initializing the Asciidoctor instance.
Yes, the class could be created lazily and a mutex could guarantee mutual exclusion so that the class is created only once.
Are there any implications of this pull request? …
> Fix 1158 concurrent conversion to stream

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Catalog.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/ImageReference.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Link.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/CatalogImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ImageReferenceImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/LinkImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/internal/WhenReadingLinksFromCatalogAsset.java
- asciidoctorj-core/src/test/resources/sample-with-links.adoc
Expose Links in the Catalog Assest to offer the same features as in core Asciidoctor https://docs.asciidoctor.org/asciidoctor/latest/api/catalog-assets/.
Add new Link interface and accessors methods to Catalog interface.
There are also some improvements to javadocs to ImageReference.
Original links in Asciidoctor are just a string and I could have gone with just that. But I decided to wrap them in an Java interface to protect from future evolutions. I can imagine maybe at some point Link also contain information about the text or attributes being applied in the macro.
No
Fixes #1183 
Please …
> Expose Links in Catalog

- asciidoctorj-core/build.gradle
- asciidoctorj-wildfly-integration-test/build.gradle
Simplify Gradle configuration removing an unnecessary configuration, see #1188 for details
Just removes it, no other changes are necessary, reports path in CI still match.
No :thinking: 
No
Fixes #1188 
This is an internal change, I don't think it's worth adding to changelog.
> Remove unnecessary tests reports destination

- asciidoctorj-core/build.gradle
- asciidoctorj-wildfly-integration-test/build.gradle
Simplify Gradle configuration removing an unnecessary configuration, see #1188 for details
Just removes it, no other changes are necessary, reports path in CI still match.
No :thinking: 
No
Fixes #1188 
This is an internal change, I don't think it's worth adding to changelog.
> (v2.5.x) Remove unnecessary tests reports destination

- CHANGELOG.adoc
- README.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/PreprocessorTest.java
- asciidoctorj-core/src/test/resources/document-with-arrays.adoc
- chocolatey/asciidoctorj.nuspec
- docs/modules/ROOT/pages/installation.adoc
- docs/modules/ROOT/pages/safe-mode-and-filesystem-access.adoc
- docs/modules/guides/pages/optimization.adoc
Fix invalid http://asciidoctor.org references found in docs and JavaDocs.
* Applied https where applicable
* Updated JavaDoc references to current links in https://docs.asciidoctor.org/
No.
No.
Fixes #1195 
> Fix invalid http://asciidoctor.org references

- CHANGELOG.adoc
- asciidoctorj-core/build.gradle
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAnAsciidoctorClassIsInstantiatedInAnEnvironmentWithGemPath.java
- asciidoctorj-core/src/test/java/org/asciidoctor/categories/Polluted.java
- build.gradle
Simplify Gradle build and fix some IDE integration issues. See #1193 for details.
* Add junit-pioneer to inject environment variables into tests. This allows removing custom Gradle task pollutedTest and running them normally.
* Refactor WhenAnAsciidoctorClassIsInstantiatedInAnEnvironmentWithGemPath as a parametrized tests.
* Add missing cases for Asciidoctor Factory in WhenAnAsciidoctorClassIsInstantiatedInAnEnvironmentWithGemPath.
Discussed in #1193.
No, if anything, it should be easier for contributors now.
Fixes #1193
Please add …
> Use junit-pioneer to simplify polluted tests

- CHANGELOG.adoc
- README.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/test/resources/document-with-arrays.adoc
- chocolatey/asciidoctorj.nuspec
- docs/modules/ROOT/pages/convert-to-epub3.adoc
- docs/modules/ROOT/pages/installation.adoc
- docs/modules/ROOT/pages/safe-mode-and-filesystem-access.adoc
- docs/modules/guides/pages/optimization.adoc
Port of PR https://github.com/asciidoctor/asciidoctorj/pull/1196, but for branch v2.5.x.
From here :point_down:, the same stuff as in the other PR.
Fix invalid http://asciidoctor.org references found in docs and JavaDocs.
* Applied https where applicable
* Updated JavaDoc references to current links in https://docs.asciidoctor.org/
No.
No.
Fixes #1195 
> (v2.5.x) Fix invalid http://asciidoctor.org references

- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
Test compatibility with the latest Boot version v2.7.12 in main v2.5.x.
We use Boot branch 2.x which is still Java 8 compatible.
Bump Boot version in IT.
No.
No.
Just a chore, not worth documenting imho
> (v2.5.x) Bump Spring Boot in IT to latest v2.7.12

- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
Test compatibility with the atest Boot version v3.1.0 in main branch.
Bump Boot version in IT.
No.
No.
Just a chore, not worth documenting imho
> (main) Bump Spring Boot in IT to latest v3.1.0

- docs/modules/guides/nav.adoc
- docs/modules/guides/pages/api-migration-guide-v25x-to-v30.adoc
- docs/modules/guides/partials/update-macro-api.adoc
- docs/modules/guides/partials/update-preprocessor-api.adoc
This PR documents the breaking changes to the processor API in the migration guide from 2.5.x to 3.x.x.
(Please note that I used ChatGPT to rephrase parts of that text to better convey the necessary steps, I often find myself writing texts that native speakers are not able to follow (guess whose fault that is 😜))
> Document breaking changes to processors in migration guide

- CHANGELOG.adoc
- build.gradle
Simply bump JRuby to latest.
JRuby has fixed some CVEs and while we are unaffected, bumping avoids warnings in users scans.
Bump the `jrubyVersion` property.
Closes #1215 
> V2.5.x bump jruby to 9.4.2.0

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Block.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/ContentNode.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/DescriptionList.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/DescriptionListEntry.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/List.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/PhraseNode.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Section.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/StructuralNode.java
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Table.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/AuthorImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/BlockImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ContentNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/DescriptionListImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ListImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/PhraseNodeImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/RowImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/SectionImpl.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/StructuralNodeImpl.java
- docs/modules/guides/pages/api-migration-guide-v25x-to-v30.adoc
- docs/modules/guides/partials/removal-of-deprecated-methods-in-ast-package.adoc
- docs/modules/guides/partials/removal-of-deprecated-methods-in-extension-package.adoc
Remove deprecated methods in `ast` package.
Simply remove the code marked as deprecated and adding migration docs.
no
Users will need to update their code if they use some of the removed methods.
The PR includes a migration guide.
Fixes #1204 
> Remove deprecated from ast package

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
Avoid unnecessary CI runs when modifying docs.
Docs are built from [docs.asciidoctor.](https://github.com/asciidoctor/docs.asciidoctor.org), we could have a job to build the docs and ensure they are correct, but right now this is using hardware resources for nothing :earth_africa: :leaves: .
Use `paths-ignore` to ignore the 'docs/**' path.
No
No
Fixes #Issue 
> (v2.5.x) Ignore docs in ci

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
Avoid unnecessary CI runs when modifying docs.
Docs are built from [docs.asciidoctor.](https://github.com/asciidoctor/docs.asciidoctor.org), we could have a job to build the docs and ensure they are correct, but right now this is using hardware resources for nothing :earth_africa: :leaves: .
Use `paths-ignore` to ignore the 'docs/**' path.
No
No
Fixes #Issue 
> (v3.0.x) Ignore docs folder in CI

- docs/antora.yml
Prepare metadata to publish the docs as pre-release.
I tested building the docs from the playbook from https://github.com/asciidoctor/docs.asciidoctor.org and it worked well.
Both versions appear...btw, I will remove v2.4 from the published docs, last release was Feb 21, no point in keeping the docs since that version is no longer maintained.
When clicking on the "AsciidoctorJ" title, 2.5 is loaded by default :ok_hand: 
Update the metadata, after that, I'll create the PR to http://github.com/asciidoctor/docs.asciidoctor.org to remove v2.4 and publish v3.0.x as a pre-release …
> (v3.0.x) Update Antora metadata for v3.0.0-alpha.1 prerelease

- docs/antora.yml
Update Antora metadata for branch v2.5.x
Simply update `antora.yml` file.
No
No
*If this PR fixes an open issue, please add a line of the form:*
No issue.
*Please add a corresponding entry to the file CHANGELOG.adoc.*
I don't think it makes sense, this metadata will be updated in the docs as soon as they are updated (nightly iirc).
It's not something that depends on a release.
> (v2.5.x) Fix antora metadata

- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenDocumentContainsDitaaDiagram.java
- asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenEpub3BackendIsUsed.java
- asciidoctorj-distribution/src/test/resources/epub/content-document.adoc
- asciidoctorj-distribution/src/test/resources/epub/epub-index.adoc
- asciidoctorj-distribution/src/test/resources/sample-with-diagram.adoc
- build.gradle
- Update distribution dependencies according to https://github.com/asciidoctor/asciidoctorj/issues/1227.
`asciidoctorj-diagram` is excluded since v2.2.8 is not compatible with Java 8 and this branch still is.
- Ported a tests from asciidoctorj-diagram to detect issues with it diagram and epub.
Simply bumps the dependencies.
no, that I know off :shrug: 
Does not close any issue directly
> (v2.5.x) Update distributions dependencies

- CHANGELOG.adoc
- build.gradle
JRuby 9.4.3.0 includes an updated Psych YAML library, which uses SnakeYAML-Engine and avoids several CVEs against the original SnakeYAML. By updating here, downstream users of asciidoctorj will not run into security audit issues.
See related issues and PRs:
* https://github.com/jruby/jruby/issues/7570
* https://github.com/jruby/jruby/pull/7600
* https://github.com/jruby/jruby/pull/7626
* https://github.com/jruby/jruby/issues/7935
* Update JRuby to get a version that does not use CVE-ridden SnakeYAML
* Updates JRuby to 9.4.3.0
* Not …
> Update to JRuby 9.4.3.0

- CHANGELOG.adoc
- build.gradle
This PR just takes #1234 and puts it on top of the v2.5.x branch.
Cherry picked the commit from @headius.
Yes.
See #1234 
Fixes #Issue 
> Upgrade jruby 2.5.x

- CHANGELOG.adoc
- asciidoctorj-api/build.gradle
- asciidoctorj-cli/build.gradle
- asciidoctorj-core/build.gradle
The module names I picked are in accordance with those of OSGi bundles.
If you don't like the names, I will change them.
Fixes #1239 
I added a line to CHANGELOG.adoc.
> Reserve stable module names for future JPMS modularization

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java
- asciidoctorj-core/src/test/resources/relative/sub/test.adoc
Make the CLI set the :mkdirs option.
Similar to the implementation of Asciidoctor it sets the option :mkdirs if the input is not read from stdin.
Fixes #1241
> CLI should set :mkdirs option by default (#1241)

- CHANGELOG.adoc
- build.gradle
Fix issue #1035 as commented https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/553#issuecomment-1793240139
Yes, validated in maven runs and also building a custom distribution of AsciidoctorJ.
n/a
The only thing is that there's still another warning for Java > 13. But we can treat it in a separated PR.
```
OpenJDK 64-Bit Client VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release
```
Fixes #1035
> Bump JRuby to v9.4.5.0 (fixes #1035)

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/ContentNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ContentNodeImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/ContextChangeTest.java
Adding a function to set the Context of a node.
Added a setContext function to the ContentNode
Possibly.
Not that I know of.
Fixes #Issue 
> Moved context functions to ContentNode

- asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java
- asciidoctorj-api/src/main/java/org/asciidoctor/Options.java
- asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java
- asciidoctorj-cli/src/main/java/org/asciidoctor/cli/AsciidoctorCliOptions.java
- asciidoctorj-cli/src/main/java/org/asciidoctor/cli/jruby/AsciidoctorInvoker.java
- asciidoctorj-cli/src/main/java/org/asciidoctor/cli/jruby/AsciidoctorRubyInvoker.java
- asciidoctorj-cli/src/test/java/org/asciidoctor/cli/WhenAsciidoctorAPICallIsCalled.java
- asciidoctorj-cli/src/test/java/org/asciidoctor/cli/WhenAsciidoctorIsCalledUsingCli.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/GlobDirectoryWalker.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyGemsPreloader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyHashUtil.java
- asciidoctorj-core/src/main/resources/org/asciidoctor/jruby/internal/asciidoctorclass.rb
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenGlobExpressionIsUsedForScanning.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
- asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
This PR should do the same thing as #1248, that is better align the behavior of the AsciidoctorJ CLI with the behavior of the Asciidoctor Ruby CLI.
This PR however, reuses the original Asciidoctor::Cli::Invoker and feeds its own options into it instead of letting Asciidoctor Ruby parse them.
So chances are that this works a bit better than the other PR.
The code is still raw, but I'd like to get some feedback on what approach to pursue.
If this PR fixes an open …
> Reuse Asciidoctor Ruby invoker

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/ContentNode.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ContentNodeImpl.java
- asciidoctorj-core/src/test/java/org/asciidoctor/jruby/ast/impl/ContextChangeTest.java
Added unit test for changing the context: ContextChangeTest.java (#1250) Reformatting the setContext function.
Added entry to CHANGELOG.adoc
(cherry picked from commit 43154994a316728363286bd42894536fa9af6b15)
Add setContext function to ContentNode
By adding a new function and unit test
Probably not
Used a cherry-pick to bring the function over; there are a lot of @deprecated statements that have appeared too.
Worth checking before rebasing.
If this PR fixes an …
> Add setContext function

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/extension/Reader.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/internal/ReaderImpl.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorIsRegistered.groovy
https://github.com/asciidoctor/asciidoctorj/issues/1262#issuecomment-1960031235 mentioned that AsciidoctorJ is currently missing the methods Reader.getSource() and Reader.getSourceLines().
This PR adds the missing methods.
Add the methods.
No.
No, it just adds new methods to the API.
It is related to #1262, but doesn't fix it, since the issue complains about the docs.
> Add methods Reader.getSource and Reader.getSourceLines

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Table.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/TableImpl.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/GithubContributorsBlockMacro.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockMacroProcessorCreatesATable.groovy
- config/codenarc/codenarc.groovy
Add support for setting the width of table columns.
While columns have a method `setWidth()` that sets the attribute `width` of a column, this does not become effective.
In addition it is required to set the attribute `colpcwidth`, which Asciidoctor core only sets internally when calling Table#assign_column_widths.
This PR adds a method Table.assignColumnWidths which calls the Ruby method mentioned above.
Very likely.
There should be no change of existing …
> Fixes #1265. Support setting column widths

- CHANGELOG.adoc
- asciidoctorj-api/src/main/java/org/asciidoctor/ast/Table.java
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/TableImpl.java
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/GithubContributorsBlockMacro.groovy
- asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockMacroProcessorCreatesATable.groovy
- config/codenarc/codenarc.groovy
This PR fixes the issue mentioned in #1265.
Column.setWidth will be honored if an extension calls Table#assignColumnWidths() after setting the column widths and adding the columns to the table (in addition to establishing the parent-child-relationship).
Column widths could be assigned whenever a column is added to a table, or when Column.setWidth is invoked.
This change would be very intrusive though. 
Therefore, I found it better to have a way that requires calling a new method.
Are there any implications of this pull request? Anything …
> Support column widths 2.5.x

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
- build.gradle
This PR updates the asciidoctor gem to the latest version 2.0.23.
It also updates JRuby and asciidoctorj-epub3 to the latest versions.
> Update asciidoctor 2.0.23

- chocolatey/README.adoc
- chocolatey/asciidoctorj.nuspec
- chocolatey/tools/chocolateyinstall.ps1
Update the Chocolatey package at https://community.chocolatey.org/packages/asciidoctorj to AsciidoctorJ 2.5.13.
It updates the chocolatey assets.
Fixes #Issue 
> Chocolatey: Upgrade packaging to 2.5.13

- CHANGELOG.adoc
- build.gradle
The build does not work anymore since a few weeks because a couple of dependencies cannot be resolved anymore, namely grolifant and okhttp-digest.
This PR tries to fix the build again.
Move the dependency on the plugin to an old style plugin dependency, and specify an explicit dependency on grolifant.
Probably.
For example getting rid of Gradle altogether, or installing gems with some other mechanism, like Maven.
Fixes #1275
> Fixes #1275. Fix unresolved dependency grolifant and okhttp-digest

- CHANGELOG.adoc
- build.gradle
Upgrade asciidoctorj-diagram-jsyntrax to the latest version 1.38.2.
1.38.1 did not work with Java 21.
> Upgrade jsyntrax to 1.38.2

- docs/antora.yml
Fix version that appears in docs, Antora config still mentions `alpha` but the stable 3.0.0 is out.
Update config files and wait for nighly docs rebuild.
no
no
No need to reference issue or changelog imo.
> Fix version in docs: removed alpha references

- asciidoctorj-springboot-integration-test/springboot-app/build.gradle
- docs/modules/guides/pages/run-with-springboot.adoc
Update and improve Spring Boot integration docs.
* Fixed broken links to SB docs
* Added details about the need to handle transitive dependencies
* Update integration test to latest SB version 3.3.4
* How does it achieve that?*
Fixes broken links and adds clarification on transitive dependencies. 
* Are there any implications of this pull request? Anything a user must know?*
no
Fixes #1286 
*Please add a corresponding entry to the file CHANGELOG.adoc*
No need for this, the changes will go live with docs, not a release.
> (main) Update 'Running with Spring Boot' docs

- CHANGELOG.adoc
- asciidoctorj-cli/build.gradle
- build.gradle
Bump JCommander to the latest v2.0.
Update the version and the coordinates.
No.
Only artifact coordinates changed, not the packages.
~If this PR fixes an open issue, please add a line of the form:~
> Update JCommander coordinates for v2.0

- .github/workflows/continuous-integration.yaml
- CHANGELOG.adoc
The CI build currently fails on Windows because it uses a deprecated version of the gh action upload-artifact.
This PR should fix the windows build again.
Upgrade the version of the upload-artifact action.
Yes, disable the windows build. But it's better to keep it.
No.
Fixes #1294.
> Fix #1294. Upgrade upload-artifact

- CHANGELOG.adoc
- asciidoctorj-core/src/main/java/org/asciidoctor/jruby/log/internal/LogHandlerRegistryExecutor.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
- asciidoctorj-core/src/test/java/org/asciidoctor/WhenTwoAsciidoctorsLogToConsole.java
- asciidoctorj-core/src/test/java/org/asciidoctor/log/TestLogHandlerService.java
Currently, if 2 Asciidoctor instances are created from the same ClassLoader, LogHandler services discovered from the ServiceLoader are reused.
This behavior differs from how extensions are created: For every new instance of Asciidoctor, a new ServiceLoader is created with `ServiceLoader.load()` so that no extension instances from a previous Asciidoctor instance are reused.
This PR updates the behavior so that it aligns with how extensions are created, and creates a new ServiceLoader for every new Asciidoctor instance.
Fixes #1297
> Fix #1297. Create ServiceLoader for loggers per Asciidoctor instance

- CHANGELOG.adoc
- build.gradle
Fixes CVE-2025-46551
Closes #1301
Simple bump
n/a
n/a
Fixes #1301 
> Bump JRuby from v9.4.9.0 to v9.4.12.1

- asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
- build.gradle
Bump test dependencies:
- arquillian from 1.6.0.Final to 1.9.2.Final
- commons-io from 2.15.1 to 2.19.0
- hamcrest from 1.3 to 2.2
- junit-pioneer from 2.2.0 to 2.3.0
- Assertj from 3.24.2 to 3.27.3
- Netty from 4.1.58.Final to 4.2.2.Final
- saxon-HE 9.9.0-2 from 9.9.1-8
- PDF-box from 3.0.0 to 3.0.5
- Groovy from 3.0.17 to 3.0.25
Also, remove a couple of unused configs.
n/a
no
> Bump test dependencies
