asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
asciidoctorj-core/src/main/java/org/asciidoctor/converter/JavaConverterRegistry.java
asciidoctorj-core/src/main/java/org/asciidoctor/converter/internal/ConverterRegistryExecutor.java
asciidoctorj-core/src/main/java/org/asciidoctor/converter/spi/ConverterRegistry.java
asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java

Adds refactor for Converters API and whole AST API by providing getters and setters on methods. Also AbstractNode class has been added in AST hierarchy to match Asciidoctor Ruy structure.

Adds refactor for Converters API

---

asciidoctorj-diagram/build.gradle
asciidoctorj-diagram/gradle.properties
asciidoctorj-diagram/src/test/java/org/asciidoctor/WhenDocumentContainsDitaaDiagram.java
asciidoctorj-diagram/src/test/java/org/asciidoctor/util/ClasspathHelper.java
asciidoctorj-diagram/src/test/java/org/asciidoctor/util/ClasspathResources.java
asciidoctorj-diagram/src/test/resources/sample.adoc
build.gradle
settings.gradle

done at Hackergarten Basel January 2015 by @maximmo and @madmas

add everything to use asciidoctor-diagram as asciidoctorj-diagram

---

asciidoctorj-core/src/main/java/org/asciidoctor/GlobDirectoryWalker.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenGlobExpressionIsUsedForScanning.java

Fix for #284 
@lordofthejars If you accept this PR I would cherry-pick the commit into the master branch.

#284 Don't fail for files in root directory with absolute path

---

asciidoctorj-core/src/main/java/org/asciidoctor/Attributes.java

If this gets merged I would cherry-pick the commit into the asciidoctorj-1.6.0 branch.

Fixes #288. And added some additional Javadoc to other methods.

---

asciidoctorj-pdf/build.gradle

When merged I'll cherry-pick this commit into the asciidoctorj-1.6.0 branch

Bundle fontawesome.ttf from prawn-icon gem in asciidoctorj-pdf

---

asciidoctorj-pdf/src/test/resources/code_examples/coffeeScript.coffee
asciidoctorj-pdf/src/test/resources/code_examples/groovy.groovy
asciidoctorj-pdf/src/test/resources/sample.adoc

Since the forum request was about scala, I have added a scala example alongside with others languages.
Also some are embedded and some are included to make use we don't have an issue with this.

Related to #368: added more code highlighting examples for 'rouge'

---

asciidoctor-pdf-gem-installer.pom
asciidoctorj-pdf/build.gradle
asciidoctorj-pdf/src/test/java/org/asciidoctor/WhenBackendIsPdf.java
build.gradle
test-asciidoctor-upstream.sh

Make Travis test against asciidoctor-pdf dev as well.
This makes sense as asciidoctorj-pdf now also tests on how the PDF eventually looks like after recent additions from @abelsromero with #376

Test pdf upstream

---

asciidoctorj-core/src/main/java/org/asciidoctor/extension/DocinfoProcessor.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenStructuredDocumentIsRequired.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
build.gradle

Upgraded the dependency on Asciidoctor for the master! branch.
This is to prepare a release of AsciidoctorJ 1.5.3.

Upgrade to Asciidoctor 1.5.3 and JRuby 1.7.22

---

README.adoc

Leiningen is the build tool of Clojure projects.

Explained how to add the dependency in Leiningen

---

.travis.yml
appveyor.yml
asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenPlantumlDiagramIsRendered.java

This PR is for now just a playground to get PlantUML/graphviz diagram generation tested on our CI systems.

Test Plantuml diagram generation

---

README.adoc

to match AsciidoctorJ 1.5.4 API

fixed attributes -> getAttributes in sample code

---

test-asciidoctor-upstream.sh

* update script to handle new gemspec contents
* only run upstream test on first job in build

resolves #483 fix test against upstream

---

.travis.yml
asciidoctorj-core/gradle.properties
asciidoctorj-diagram/gradle.properties
asciidoctorj-distribution/build.gradle
asciidoctorj-epub3/gradle.properties
asciidoctorj-pdf/gradle.properties
build.gradle
gradle/deploy.gradle
gradle/deploySnapshot.gradle
gradle/publish.gradle
gradle/signing.gradle
gradle/versioncheck.gradle
gradle/wrapper/gradle-wrapper.properties
test-asciidoctor-upstream.sh

This PR tries to get the recent changes/fixes to the publishing originally done by @ancho on the master branch also to the asciidoctorj-1.6.0 branch.
Instead of cherry picking the multiple commits I tried to apply them manually, would be great if somebody could review.
Also cherry-picked the checkVersion build steps.

Publishing fixes for the 1.6.0 branch 

---

asciidoctorj-core/src/main/java/org/asciidoctor/Options.java
asciidoctorj-core/src/main/java/org/asciidoctor/OptionsBuilder.java

Improve the toFile documentation about file vs. string output

---

asciidoctorj-diagram/gradle.properties
build.gradle

Bump version of the asciidoctor gem to 1.5.5 and asciidoctor-diagram to 1.5.1.

Asciidoctor 1.5.5

---

asciidoctorj-diagram/gradle.properties
asciidoctorj-diagram/src/test/java/org/asciidoctor/WhenDocumentContainsDitaaDiagram.java
asciidoctorj-distribution/src/test/groovy/org/asciidoctor/diagram/WhenDitaaDiagramIsRendered.groovy
build.gradle

Bump asciidoctor to 1.5.5 and asciidoctor-diagram to 1.5.1 on the 1.6.0 branch.

Asciidoctor 1.5.5 1.6.0

---

asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractBlockImpl.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/AbstractNodeImpl.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/DocumentRuby.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/Inline.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/InlineImpl.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListImpl.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListItem.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/ListNode.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/Row.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/Table.java
asciidoctorj-core/src/main/java/org/asciidoctor/ast/TableImpl.java
asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
asciidoctorj-core/src/test/java/org/asciidoctor/converter/TextConverter.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/TerminalCommandTreeprocessor.java

Fix or suppress deprecation warnings

---

build.gradle

Maybe helps to debug failing test on travis. see #550

enable full exception format running tests with stacktrace enabled

---

README.adoc

I think we need to close the span tag

typo at TerminalCommandTreeprocessor example

---

asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java

Fixes tests against the current asciidoctor 1.5.6.dev

Fix tests against upstream

---

asciidoctorj-core/src/main/java/org/asciidoctor/extension/BlockProcessor.java
asciidoctorj-core/src/main/java/org/asciidoctor/extension/Contexts.java
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedBlockProcessor.groovy
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AttributeCheckingBlockProcessor.groovy
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenABlockProcessorCreatesABlockThatATreeProcessorVisits.groovy
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAJavaExtensionUsesCounters.groovy
asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/YellBlockProcessor.java

Fix #569 Remove leading CONTEXT prefix from all constants in @Contexts

---

README.adoc

This PR simply points potential users of the extension API to better try the 1.6.0 branch.

Added pointer to AsciidoctorJ 1.6.0 for users of the extension API

---

asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciiDocIsRenderedToDocument.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
asciidoctorj-distribution/build.gradle
build.gradle

Same fix was already applied to master.
Also bump JRuby to 9.1.13.0.

Fix upstream build 1.6.0

---

build.gradle

Update tiltGemVersion to 2.0.8

---

asciidoctorj-core/src/test/java/org/asciidoctor/WhenMultipleDocumentsAreRendered.java

Related to issue #680 
Trying to reproduce it in the CI

added test to reproduce issue with jRuby 9.1.16.0

---

asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorSetsTheSourceMapOption.groovy

This PR adds the tests for #693. 
Already approved by @mojavelinux

Added test for setting sourcemap option from a preprocessor

---

asciidoctorj-distribution/build.gradle
build.gradle
gradle/sdkman.gradle

This PR adds the publishing to sdkman again which got lost in the merge of 1.6.0 to master.

Readd sdkman

---

.gitattributes
README.adoc
chocolatey/README.adoc
chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1
chocolatey/tools/chocolateyuninstall.ps1

Create a Chocolatey .nuspec based on the Bintray -bin.zip package.
This PR is a cherry-pick from the old master that got lost in the merge from 1.6 into master.

Add Chocolatey packaging.

---

build.gradle

This PR bumps JRuby to the latest version on master.

Bump JRuby to 9.2.2.0

---

asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java
asciidoctorj-core/src/main/java/org/asciidoctor/cli/AsciidoctorInvoker.java
asciidoctorj-core/src/main/java/org/asciidoctor/internal/JRubyAsciidoctor.java
asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenSlimTemplatesAreUsed.groovy
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenExtensionsAreRegisteredAsService.groovy
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenTheConfigIsSetOfAJavaExtension.groovy
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAnAsciidoctorClassIsInstantiated.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAsciidoctorLogsToConsole.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenAttributesAreUsedInAsciidoctor.java
asciidoctorj-core/src/test/java/org/asciidoctor/WhenCustomTemplatesAreUsed.java
asciidoctorj-core/src/test/java/org/asciidoctor/converter/WhenConverterIsRegistered.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenReaderIsManipulatedInExtension.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionGroupIsRegistered.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenRubyExtensionIsRegistered.java

Mark render* methods as deprecated (and replace usage)

---

asciidoctorj-wildfly-integration-test/build.gradle
asciidoctorj-wildfly-integration-test/src/test/resources/arquillian.xml
build.gradle

I found out the Maven coordinates of the wildfly distribution (no idea why I didn't find it before, I feel stupid), so we should also run the Wildfly integration test on the CI servers.

Run Wildfly integration test on CI

---

README.adoc
asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java

This PR is a cherry-pick of #765 for the 1.6.x branch.

Osgi update 1.6.x

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Switch to a SHA256 sum and add an icon URL while we're here.

Chocolatey: Upgrade packaging to 1.6.2.

---

asciidoctorj-api/src/main/java/org/asciidoctor/ast/Section.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/SectionImpl.java
asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenADocumentContainsNumberedSections.groovy

Resolves #549 
There's not much to this.  Most of the work was done on the Ruby side.

Add section numeral API

---

gradle/wrapper/gradle-wrapper.properties
gradlew

chore: upgrade to Gradle 5.6.3

---

README.adoc

No idea why I got this wrong...

Fix badge URL

---

asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java

JCommander has been updated and now passes '-' as an input File when encountered

restore STDIN input

---

CHANGELOG.adoc
build.gradle

[ ] Bug fix
[X] New non-breaking feature
Update included artifact of asciidoctorj-pdf

Upgrade to asciidoctorj-pdf 1.5.0-beta.8

---

CHANGELOG.adoc
build.gradle

[ ] Bug fix
[X] New non-breaking feature
Upgrade asciidoctorj-diagram to the latest version 2.0.0.

Upgrade asciidoctorj-diagram to 2.0.0

---

CHANGELOG.adoc
README.adoc
build.gradle

A simple dependency upgrade
I believe #631 and #659 should be closed, they were fixed even earlier.

Bump Asciidoctor EPUB3 to 1.5.0-alpha.13

---

CHANGELOG.adoc
README.adoc
build.gradle

Bump Asciidoctor EPUB3 to 1.5.0-alpha.14

---

CHANGELOG.adoc
README.adoc
build.gradle

Bump Asciidoctor EPUB3 to 1.5.0-alpha.15

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

https://chocolatey.org/docs/create-packages recommends using a CDN for
icons. Switch to Statically.
I recently updated the AsciidoctorJ package at https://chocolatey.org/packages/asciidoctorj.
This reflects that change.
Bumps the version number in a couple of places.
It might make sense update the versions prior to tagging.
Not that I'm aware.
Fixes #Issue 
Please add a corresponding entry to the …

Chocolatey: Upgrade packaging to 2.3.0.

---

CHANGELOG.adoc
build.gradle

Upgrade Ruby and remove all illegal access warnings.
Fixes #Issue 

Upgrade to jruby-9.2.12.0

---

CHANGELOG.adoc
README.adoc
test-asciidoctor-upstream.sh

Fixes refences to TravisCI in README and removes deprecated badge.
Corrects content of README.
:man_shrugging: 
No
Fixes #Issue 
:heavy_check_mark: 

Fixes #929. Replace references to Travis by GHActions in README

---

CHANGELOG.adoc
README.adoc
build.gradle

Upgrades asciidoctorj-epub3 to 1.5.0-alpha.17

Upgrade asciidoctorj-epub3 to 1.5.0-alpha.17

---

CHANGELOG.adoc
build.gradle

Just bumps JRuby to the latest and greatest version.

Upgrade JRuby to 9.1.13.0

---

asciidoctorj-documentation/src/main/asciidoc/extension-migration-guide.adoc
asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc
docs/extension-migration-guide.adoc
docs/integrator-guide.adoc

Apply changes in #950
Sure, there's a degree of subjetivity in docs. But avoid this, I tried to keep changes simple.
No
Fixes #Issue 
Please add a corresponding entry to the file CHANGELOG.adoc[](url)

closes #950: refactors extensions docs + adds ExtensionGroup documentation

---

asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/converter/TextConverterTest.java
docs/integrator-guide.adoc

Fix a paste error.
Fixes #959
I'm guessing this is not necessary for such a small doc fix.

Fix code snippit error in Integrator's Guide

---

asciidoctorj-documentation/build.gradle
docs/extension-migration-guide.adoc
docs/integrator-guide.adoc

Please see #961.
Fixes #961
I don't think this merits a mention in CHANGELOG - let me know.

Add a DO NOT EDIT header to generated adoc files

---

CHANGELOG.adoc
build.gradle
docs/integrator-guide.adoc

Upgrade dependencies to Asciidoctor 2.0.11, rouge and CodeRay.
Fixes #Issue 

Upgrade Asciidoctor to 2.0.11

---

chocolatey/README.adoc
chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Upgrade the Chocolatey packaging to 2.4.2.
Update version numbers and SHS256 sum. The new package is currently going through the moderation process at https://chocolatey.org/packages/asciidoctorj/2.4.2.

Chocolatey: Upgrade packaging to 2.4.2.

---

CHANGELOG.adoc

* change log lists changes from 2.4.2 to be unreleased
* updating the change log
* no
* no

mark changes from 2.4.2 to be released

---

docs/modules/extensions/pages/include-processor.adoc

Goal of the PR is to improve a few bits of (imo) odd grammar on the page and the one spelling mistake I spotted while I glanced at the page.

Grammar tweaks to include processor extension page

---

CHANGELOG.adoc
gradle/sdkman.gradle

Fix URL for distribution in sdkman

---

CHANGELOG.adoc
asciidoctorj-springboot-integration-test/springboot-app/build.gradle
docs/modules/guides/nav.adoc
docs/modules/guides/pages/run-with-springboot.adoc

*Add guide to docs about SpringBoot quirks.*
*Adds new page `Running AsciidoctorJ with Spring Boot`*
*Not.*
*Also updates the test. I run some extra tests and current versions does not require exclusion of jRuby.*
Fixes #Issue 

Add SpringBoot guide and update example

---

README.adoc
docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/cli.adoc
docs/modules/ROOT/pages/convert-to-epub3.adoc
docs/modules/ROOT/pages/distribution.adoc
docs/modules/guides/pages/use-prerelease-version.adoc
docs/modules/project/pages/continuous-integration.adoc

Removed documentation that is available on docs.asciidoctor.org from the README.
Adding the steps to build and publish a new release to Maven central.
Additionaly I removed content from the README that is also available on the Antora site.
Imo this is too detailed for a README anyway, and duplication rather results in diverging information.
I also updated the docs for how to build in the Antora module, I wonder though if this rather only belongs in the README.
@abelsromero @mojavelinux Would be great if you could skim over this.
Are …

Add release description to README.

---

README.adoc

Similar to the change to the Asciidoctor README this PR adds the badge linking to the Zulip Asciidoctor chat.

Zulip link

---

asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JavaExtensionRegistryImpl.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/BlockMacroRegistrationTest.java

See #897
Improve method getName in JavaExtensionRegistryImpl, to support recursive search for an @Name annotation.
maybe, we can discuss it.
I only provide currently a new test in the class BlockMacroRegistrationTest, i think we have to add it to the other RegistrationTests also.
Fixes #897 
Name annotation can used as a meta-annotation

start implement feature to use @Name annotation as meta-annotation

---

README.adoc
build.gradle
chocolatey/README.adoc
chocolatey/asciidoctorj.nuspec
docs/antora.yml
gradle/sdkman.gradle

Started only wanting to remove Bintray references but added other fixes found.
* Remove bintray references
* Replace discuss by Zulip
* Remove unused attributes in README
* Update jruby-version to 9.2.17.0 (in docs)
Applies small fixes in the docs and comments.
No.
No.
Fixes #Issue 

Several doc fixes (remove bintray references, replace discuss by Zulip, ...)

---

asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java
asciidoctorj-api/src/main/java/org/asciidoctor/ast/Cursor.java
asciidoctorj-api/src/main/java/org/asciidoctor/log/LogHandler.java
asciidoctorj-api/src/main/java/org/asciidoctor/log/LogRecord.java

Minnor improvements to the Asciidoctor javadocs and some related classes.
Fixes #Issue 

Asciidoctor interface JavaDoc improvements

---

CHANGELOG.adoc
build.gradle
gradle/wrapper/gradle-wrapper.properties

Just upgrade to the latest version of Asciidoctor, 2.0.13.
Also switched to Gradle 7.0 from the RC.
Fixes #Issue 

Upgrade to Asciidoctor 2.0.13

---

.github/workflows/continuous-integration.yaml
CHANGELOG.adoc
README.adoc
asciidoctorj-core/src/test/resources/document-with-arrays.adoc
chocolatey/asciidoctorj.nuspec
test-asciidoctor-upstream.sh

Since the default branch is now "main" the Github actions are not triggered anymore.
This PR wants to fix this again.
Fixes #Issue 

Run GH actions for main branch

---

CHANGELOG.adoc
build.gradle

Upgrade Asciidoctor to 2.0.14.

Upgrade to Asciidoctor 2.0.14

---

.github/workflows/continuous-integration.yaml
.github/workflows/upstream-build.yaml

Update gh-actions components to latest versions.
Updates the version to v2 and adds new mandatory fields.
No
No
Fixes #Issue 

Bump actions/checkout and actions/setup-java

---

asciidoctorj-api/build.gradle

It seems like it is not possible anymore to run or debug a single test in IntelliJ anymore since very recently.
This PR tries to fix this.
My last status was that IntelliJ complained about the annotation org.osgi.annotation.Export not being available.
Changing the dependency type from compileOnly to implementation seems to solve this situation.
(Don't ask me why, I don't understand why compileOnly is not good here either)
@abelsromero As you were also facing this issue, could you please test this?
Fixes #Issue 
Please add a …

Try to fix running tests in IntelliJ

---

CHANGELOG.adoc
build.gradle

Just upgrades Asciidoctor to the latest and greatest version

Upgrade to Asciidoctor 2.0.15

---

docs/antora.yml

Update Antora descriptor with current version in main branch so we can point to it and publish 2.5.x docs in docs.asciidoctor.org site.
Update antora file.
No
No
Fixes #Issue 

Update version to 2.5 in Antora descriptor

---

CHANGELOG.adoc
build.gradle

This PR upgrades asciidoctorj-epub3 to the latest and greatest version 1.5.1

Upgrade asciidoctorj-epub3 to 1.5.1

---

CHANGELOG.adoc
build.gradle

Upgrade asciidoctorj-pdf to 1.6.0.
Fixes #Issue 

Upgrade to asciidoctorj-pdf 1.6.0

---

CHANGELOG.adoc
build.gradle
gradle/publish.gradle

https://github.com/gradle-nexus/publish-plugin is the new replacement for the Gradle Nexus Staging Plugin and Nexus Publish Plugin duo.
This PR updates the build to use this new plugin.
Fixes #Issue 

Upgrade to new gradle-nexus.publish-plugin

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update the Chocolatey package to 2.5.1.
Updates the version numbers in the Chocolatey assets.

Chocolatey: Upgrade packaging to 2.5.1.

---

.github/workflows/upstream-build.yaml
test-asciidoctor-upstream.sh

What is the goal of this pull request? To fix the build against upstream.
How does it achieve that? It uses the branch specified in the payload in the correct place.
Are there any alternative ways to implement this? No.
Are there any implications of this pull request? Anything a user must know? It will fix the build in Asciidoctor core.
Fixes #1050

resolves #1050 fix upstream build to build against the specified ref

---

asciidoctorj-core/build.gradle
build.gradle

Upgrade Asciidoctor to the latest and greatest version, 2.0.16.
Fixes #Issue 

Update Asciidoctor to 2.0.16

---

.github/workflows/continuous-integration.yaml
gradle/wrapper/gradle-wrapper.properties

Add support for Java 17.
Adds automated tests and any other build/code related change.
:man_shrugging: we'll see...
Added matrix to Windows build to test Java 11 and 17.
Fixes #Issue 

Add Java17 to gh-actions

---

.github/workflows/continuous-integration.yaml

Fixes in pipelines
* Execution exclude for mac-os was not aplied ('1.x' syntax no longer works)
* Test upstream 'if' condition was not being applied ever. Not it runs on ubuntu for 11 & 17
* Increase max-parellel to 4 to shorten total time
No that I know.
I'd also like to split "Test upstream" in a different job so it's shown in the actions UI and we don't miss it again.
It will require some config duplication but I think it's worth it.
If this PR fixes an open …

Fixes for CI pipelines

---

README.adoc
docs/antora.yml
docs/modules/ROOT/pages/logs-handling.adoc

Clarify default logging behavior and update released versions in docs

---

CHANGELOG.adoc
docs/modules/extensions/pages/conversion-process-overview.adoc

This PR clarifies the documentation wrt the execution order of extensions.

Fixes #1068. Clarify execution order of extensions

---

CHANGELOG.adoc
build.gradle

Just upgrades asciidoctorj-pdf and rouge.

Upgrade to asciidoctorj-pdf 1.6.2

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Upgrade the Chocolatey packaging assets to 2.5.3.
Sets proper version numbers and file hash.
Fixes #Issue 

Chocolatey: Upgrade packaging to 2.5.3.

---

docs/antora.yml

Update the artifact versions for docs.asciidoctor.org/asciidoctorj
Fixes #Issue 

Update artifact versions in docs

---

CHANGELOG.adoc
build.gradle
gradle.properties

This PR upgrades asciidoctor-pdf to the latest and greatest version.
Upgrade the dependency.
This is a breaking change since it bumps to a new major version of asciidoctor-pdf.
Even if the API did not change with this PR, documents might be rendered differently.
Fixes #Issue 

Upgrade asciidoctorj-pdf to 2.0.6

---

.github/workflows/continuous-integration.yaml

Also build PRs against 2.5.x.
Fixes #Issue 

Also build PRs for maintenance branch v2.5.x

---

CHANGELOG.adoc
build.gradle
gradle.properties

Release 2.5.5

---

docs/modules/ROOT/pages/cli.adoc
docs/modules/ROOT/pages/conversion-examples.adoc
docs/modules/ROOT/pages/read-document-tree.adoc
docs/modules/ROOT/pages/ruby-runtime.adoc
docs/modules/ROOT/partials/safe-modes.adoc
docs/modules/extensions/pages/ast-introduction.adoc
docs/modules/extensions/pages/block-macro-processor.adoc
docs/modules/extensions/pages/conversion-process-overview.adoc
docs/modules/extensions/pages/extensions-introduction.adoc
docs/modules/extensions/pages/treeprocessor.adoc
docs/modules/guides/pages/run-with-springboot.adoc
docs/modules/project/pages/project-layout.adoc
docs/modules/syntax-highlighting/pages/static-during-conversion.adoc

Proofread documentation

---

docs/modules/ROOT/pages/cli.adoc
docs/modules/ROOT/pages/conversion-examples.adoc
docs/modules/ROOT/pages/read-document-tree.adoc
docs/modules/ROOT/pages/ruby-runtime.adoc
docs/modules/ROOT/partials/safe-modes.adoc
docs/modules/extensions/pages/ast-introduction.adoc
docs/modules/extensions/pages/block-macro-processor.adoc
docs/modules/extensions/pages/conversion-process-overview.adoc
docs/modules/extensions/pages/extensions-introduction.adoc
docs/modules/extensions/pages/treeprocessor.adoc
docs/modules/guides/pages/run-with-springboot.adoc
docs/modules/project/pages/project-layout.adoc
docs/modules/syntax-highlighting/pages/static-during-conversion.adoc

This is a cherry-pick of #1110 into the main branch.

Cherry pick doc fixes

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update the Chocolatey package assets for AsciidoctorJ 2.5.5.
Fixes #Issue 

Chocolatey: Upgrade packaging to 2.5.5.

---

CHANGELOG.adoc
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/MaxSeverityLogHandler.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/SeverityConverter.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java
asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorIsCalledUsingCli.java

Ports back #1114 to the v2.5.x branch.
Fixes #Issue 

Cli exit code 2.5.x

---

CHANGELOG.adoc
build.gradle

Just upgrade JRuby to the latest and greatest.

Upgrade JRuby to 9.3.8.0

---

CHANGELOG.adoc
build.gradle

Just upgrade to JRuby 9.3.8.0 which has a vulnerability fix for Psych.

Upgrade to JRuby 9.3.8.0

---

CHANGELOG.adoc
build.gradle

Upgrade rouge to the latest and greatest version 3.30.0

Upgrade to Rouge 3.30.0

---

CHANGELOG.adoc
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionGroupIsRegistered.java
asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenJavaExtensionIsRegistered.java
build.gradle

Upgrade to the latest version of Asciidoctor core.

Upgrade to Asciidoctor 2.0.18

---

gradle.properties

Release 2.5.7

---

chocolatey/asciidoctorj.nuspec
chocolatey/tools/chocolateyinstall.ps1

Create a Chocolatey package for AsciidoctorJ 2.5.7.
Update the Chocolatey packaging assets for 2.5.7. The package has been submitted and approval status can be tracked at https://community.chocolatey.org/packages/asciidoctorj/2.5.7
Fixes #Issue 

Chocolatey: Upgrade packaging to 2.5.7.

---

CHANGELOG.adoc
build.gradle
ci/asciidoctor-gem-installer.pom
ci/asciidoctor-pdf-gem-installer.pom

Upgrade JRuby to the latest and greatest version, 9.4.0.0.
Fixes #Issue 

Jruby 9400

---

CHANGELOG.adoc
build.gradle

Fixes #1138. Upgrade JRuby to 9.3.10.0

---

README.adoc
docs/antora.yml
docs/modules/ROOT/pages/distribution.adoc

#1147 updated the versions and download links on docs.asciidoctor.org.
Right now only the docs from the v2.5.x branch are published. Therefore this PR brings these changes to that branch.
Squashed the commits to the main branch and cherry-picked them on top of v2.5.x.
Fixes #Issue 

Update version of asciidoctorj

---

CHANGELOG.adoc
gradle.properties

Release 2.5.8

---

gradle.properties

Prepare next release

---

CHANGELOG.adoc
build.gradle

Upgrade asciidoctorj-pdf to the latest and greatest version, 2.3.7.
Fixes #Issue 

Upgrade asciidoctorj-pdf to 2.3.7

---

CHANGELOG.adoc
build.gradle

Upgrade to the latest and greatest version of asciidoctor, 2.0.20.
Fixes #Issue 

Upgrade to asciidoctor 2.0.20

---

CHANGELOG.adoc
gradle.properties

Release 2.5.9

---

CHANGELOG.adoc
gradle.properties

Release 2.5.10

---

gradle.properties

Try to release Asciidoctorj 3.0.0-alpha.1

release 3.0.0-alpha.1

---

CHANGELOG.adoc
build.gradle

Upgrades asciidoctorj-pdf to the latest version, and also bumps jruby.
Fixes #Issue 

Upgrade asciidoctorj-pdf and jruby

---

CHANGELOG.adoc
gradle.properties

Prepare the next release of the v2.5.x branch, 2.5.11.

Release 2.5.11

---

gradle.properties

Prepare a new pre-release for asciidoctorj 3.0.0, 3.0.0-alpha.2.
Fixes #Issue 

Prepare release 3.0.0-alpha.2

---

README.adoc
docs/antora.yml

Fix docs references in README and antora.yml.
n/a
n/a
n/a
nop.

Update versions in docs

---

CHANGELOG.adoc
asciidoctorj-api/src/main/java/org/asciidoctor/extension/Reader.java
asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/internal/ReaderImpl.java
asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/WhenAPreprocessorIsRegistered.groovy

Same as #1264, but for the 2.5.x branch.
This tries to help with the issue reported in #1262.
Fixes #Issue 

Add methods Reader.getSource and Reader.getSourceLines

---

CHANGELOG.adoc
asciidoctorj-distribution/src/test/java/org/asciidoctor/WhenBackendIsRevealJs.java
build.gradle

This PR upgrades asciidoctor core to the latest and greatest version, 2.0.21.
Besides that, it also updates some other dependencies, like asciidoctorj-pdf, asciidoctorj-diagram, asciidoctorj-revealjs and jruby.
Fixes #Issue 

Upgrade asciidoctor 2.0.21

---

CHANGELOG.adoc
build.gradle

Upgrade asciidoctor, asciidoctor-pdf and asciidoctor-epub3 to the latest versions.
Fixes #Issue 

Upgrade asciidoctor 2.0.22

---

CHANGELOG.adoc
gradle.properties

Release 2.5.12

---

CHANGELOG.adoc
README.adoc
docs/antora.yml
gradle.properties

Release 2.5.13

---

gradle.properties

Try to release asciidoctorj 3.0.0-beta.1 after merging this.
Since I have updated the signing key, it might take a couple of attempts.

Release 3.0.0-beta.1

---

CHANGELOG.adoc
gradle.properties

This PR should be the major release of asciidoctorj 3.0.0

Release 3.0.0
